package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ControlGui generated by hbm2java
 */
@Entity
@Table(name = "control_gui", schema = "comun", catalog = "siisspolweb")
public class ControlGui implements java.io.Serializable {

	private Integer idControlGui;
	private TipoAcceso tipoAcceso;
	private TipoControl tipoControl;
	private Integer opcion;
	private String objeto;
	private String control;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<MensajeIdioma> mensajeIdiomas = new HashSet<MensajeIdioma>(0);

	public ControlGui() {
	}

	public ControlGui(Integer idControlGui, TipoAcceso tipoAcceso, TipoControl tipoControl, String control,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo) {
		this.idControlGui = idControlGui;
		this.tipoAcceso = tipoAcceso;
		this.tipoControl = tipoControl;
		this.control = control;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public ControlGui(Integer idControlGui, TipoAcceso tipoAcceso, TipoControl tipoControl, Integer opcion,
			String objeto, String control, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo, Set<MensajeIdioma> mensajeIdiomas) {
		this.idControlGui = idControlGui;
		this.tipoAcceso = tipoAcceso;
		this.tipoControl = tipoControl;
		this.opcion = opcion;
		this.objeto = objeto;
		this.control = control;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.mensajeIdiomas = mensajeIdiomas;
	}

	@Id

	@Column(name = "id_control_gui", unique = true, nullable = false)
	public Integer getIdControlGui() {
		return this.idControlGui;
	}

	public void setIdControlGui(Integer idControlGui) {
		this.idControlGui = idControlGui;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_acceso", nullable = false)
	public TipoAcceso getTipoAcceso() {
		return this.tipoAcceso;
	}

	public void setTipoAcceso(TipoAcceso tipoAcceso) {
		this.tipoAcceso = tipoAcceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_control", nullable = false)
	public TipoControl getTipoControl() {
		return this.tipoControl;
	}

	public void setTipoControl(TipoControl tipoControl) {
		this.tipoControl = tipoControl;
	}

	@Column(name = "opcion")
	public Integer getOpcion() {
		return this.opcion;
	}

	public void setOpcion(Integer opcion) {
		this.opcion = opcion;
	}

	@Column(name = "objeto", length = 100)
	public String getObjeto() {
		return this.objeto;
	}

	public void setObjeto(String objeto) {
		this.objeto = objeto;
	}

	@Column(name = "control", nullable = false, length = 100)
	public String getControl() {
		return this.control;
	}

	public void setControl(String control) {
		this.control = control;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "controlGui")
	public Set<MensajeIdioma> getMensajeIdiomas() {
		return this.mensajeIdiomas;
	}

	public void setMensajeIdiomas(Set<MensajeIdioma> mensajeIdiomas) {
		this.mensajeIdiomas = mensajeIdiomas;
	}

}
