package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DenominacionMonedaId generated by hbm2java
 */
@Embeddable
public class DenominacionMonedaId implements java.io.Serializable {

	private char moneda;
	private Integer sec;

	public DenominacionMonedaId() {
	}

	public DenominacionMonedaId(char moneda, Integer sec) {
		this.moneda = moneda;
		this.sec = sec;
	}

	@Column(name = "moneda", nullable = false, length = 1)
	public char getMoneda() {
		return this.moneda;
	}

	public void setMoneda(char moneda) {
		this.moneda = moneda;
	}

	@Column(name = "sec", nullable = false)
	public Integer getSec() {
		return this.sec;
	}

	public void setSec(Integer sec) {
		this.sec = sec;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DenominacionMonedaId))
			return false;
		DenominacionMonedaId castOther = (DenominacionMonedaId) other;

		return (this.getMoneda() == castOther.getMoneda()) && ((this.getSec() == castOther.getSec())
				|| (this.getSec() != null && castOther.getSec() != null && this.getSec().equals(castOther.getSec())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMoneda();
		result = 37 * result + (getSec() == null ? 0 : this.getSec().hashCode());
		return result;
	}

}
