package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FeriadoOficinaId generated by hbm2java
 */
@Embeddable
public class FeriadoOficinaId implements java.io.Serializable {

	private Date fecha;
	private String oficina;

	public FeriadoOficinaId() {
	}

	public FeriadoOficinaId(Date fecha, String oficina) {
		this.fecha = fecha;
		this.oficina = oficina;
	}

	@Column(name = "fecha", nullable = false, length = 23)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "oficina", nullable = false, length = 4)
	public String getOficina() {
		return this.oficina;
	}

	public void setOficina(String oficina) {
		this.oficina = oficina;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FeriadoOficinaId))
			return false;
		FeriadoOficinaId castOther = (FeriadoOficinaId) other;

		return ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null && castOther.getFecha() != null
				&& this.getFecha().equals(castOther.getFecha())))
				&& ((this.getOficina() == castOther.getOficina()) || (this.getOficina() != null
						&& castOther.getOficina() != null && this.getOficina().equals(castOther.getOficina())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getOficina() == null ? 0 : this.getOficina().hashCode());
		return result;
	}

}
