package ec.org.isspol.persistence.entities.comun;

// Generated 25-abr-2017 16:35:33 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.*;

/**
 * LogNotificacion generated by hbm2java
 */
@Entity
@Table(name = "log_notificacion", schema = "comun", catalog = "siisspolweb")
public class LogNotificacion implements java.io.Serializable {

	private Integer idLogNotificacion;
	private ProcesoNotificacion procesoNotificacion;
	private String idUsuario;
	private Integer idPersona;
	private Boolean notificado;
	private String observacion;
	private String correo;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public LogNotificacion() {
	}

	public LogNotificacion(Integer idLogNotificacion,
			ProcesoNotificacion procesoNotificacion) {
		this.idLogNotificacion = idLogNotificacion;
		this.procesoNotificacion = procesoNotificacion;
	}

	public LogNotificacion(Integer idLogNotificacion,
			ProcesoNotificacion procesoNotificacion, String idUsuario,
			Integer idPersona, Boolean notificado, String observacion,
			String correo, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha,
			String modificaEquipo) {
		this.idLogNotificacion = idLogNotificacion;
		this.procesoNotificacion = procesoNotificacion;
		this.idUsuario = idUsuario;
		this.idPersona = idPersona;
		this.notificado = notificado;
		this.observacion = observacion;
		this.correo = correo;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.IDENTITY)
	@Column(name = "id_log_notificacion", unique = true, nullable = false)
	public Integer getIdLogNotificacion() {
		return this.idLogNotificacion;
	}

	public void setIdLogNotificacion(Integer idLogNotificacion) {
		this.idLogNotificacion = idLogNotificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proceso_notificacion", nullable = false)
	public ProcesoNotificacion getProcesoNotificacion() {
		return this.procesoNotificacion;
	}

	public void setProcesoNotificacion(ProcesoNotificacion procesoNotificacion) {
		this.procesoNotificacion = procesoNotificacion;
	}

	@Column(name = "id_usuario", length = 50)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_persona")
	public Integer getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Integer idPersona) {
		this.idPersona = idPersona;
	}

	@Column(name = "notificado")
	public Boolean getNotificado() {
		return this.notificado;
	}

	public void setNotificado(Boolean notificado) {
		this.notificado = notificado;
	}

	@Column(name = "observacion")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "correo")
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "creacion_usuario", length = 100)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", length = 100)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
