package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MensajeIdiomaId generated by hbm2java
 */
@Embeddable
public class MensajeIdiomaId implements java.io.Serializable {

	private Integer idControlGui;
	private Integer idIdioma;

	public MensajeIdiomaId() {
	}

	public MensajeIdiomaId(Integer idControlGui, Integer idIdioma) {
		this.idControlGui = idControlGui;
		this.idIdioma = idIdioma;
	}

	@Column(name = "id_control_gui", nullable = false)
	public Integer getIdControlGui() {
		return this.idControlGui;
	}

	public void setIdControlGui(Integer idControlGui) {
		this.idControlGui = idControlGui;
	}

	@Column(name = "id_idioma", nullable = false)
	public Integer getIdIdioma() {
		return this.idIdioma;
	}

	public void setIdIdioma(Integer idIdioma) {
		this.idIdioma = idIdioma;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MensajeIdiomaId))
			return false;
		MensajeIdiomaId castOther = (MensajeIdiomaId) other;

		return ((this.getIdControlGui() == castOther.getIdControlGui()) || (this.getIdControlGui() != null
				&& castOther.getIdControlGui() != null && this.getIdControlGui().equals(castOther.getIdControlGui())))
				&& ((this.getIdIdioma() == castOther.getIdIdioma()) || (this.getIdIdioma() != null
						&& castOther.getIdIdioma() != null && this.getIdIdioma().equals(castOther.getIdIdioma())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdControlGui() == null ? 0 : this.getIdControlGui().hashCode());
		result = 37 * result + (getIdIdioma() == null ? 0 : this.getIdIdioma().hashCode());
		return result;
	}

}
