package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Moneda generated by hbm2java
 */
@Entity
@Table(name = "moneda", schema = "comun", catalog = "siisspolweb")
public class Moneda implements java.io.Serializable {

	private char moneda;
	private String nombre;
	private String simbolo;
	private String internacional;
	private byte redondeo;
	private double limiteCero;
	private Boolean monedaLocal;
	private String codigoCamara;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<DenominacionMoneda> denominacionMonedas = new HashSet<DenominacionMoneda>(0);

	public Moneda() {
	}

	public Moneda(char moneda, String nombre, String simbolo, String internacional, byte redondeo, double limiteCero,
			Boolean monedaLocal, String codigoCamara, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.moneda = moneda;
		this.nombre = nombre;
		this.simbolo = simbolo;
		this.internacional = internacional;
		this.redondeo = redondeo;
		this.limiteCero = limiteCero;
		this.monedaLocal = monedaLocal;
		this.codigoCamara = codigoCamara;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Moneda(char moneda, String nombre, String simbolo, String internacional, byte redondeo, double limiteCero,
			Boolean monedaLocal, String codigoCamara, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo,
			Set<DenominacionMoneda> denominacionMonedas) {
		this.moneda = moneda;
		this.nombre = nombre;
		this.simbolo = simbolo;
		this.internacional = internacional;
		this.redondeo = redondeo;
		this.limiteCero = limiteCero;
		this.monedaLocal = monedaLocal;
		this.codigoCamara = codigoCamara;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.denominacionMonedas = denominacionMonedas;
	}

	@Id

	@Column(name = "moneda", unique = true, nullable = false, length = 1)
	public char getMoneda() {
		return this.moneda;
	}

	public void setMoneda(char moneda) {
		this.moneda = moneda;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "simbolo", nullable = false, length = 10)
	public String getSimbolo() {
		return this.simbolo;
	}

	public void setSimbolo(String simbolo) {
		this.simbolo = simbolo;
	}

	@Column(name = "internacional", nullable = false, length = 3)
	public String getInternacional() {
		return this.internacional;
	}

	public void setInternacional(String internacional) {
		this.internacional = internacional;
	}

	@Column(name = "redondeo", nullable = false)
	public byte getRedondeo() {
		return this.redondeo;
	}

	public void setRedondeo(byte redondeo) {
		this.redondeo = redondeo;
	}

	@Column(name = "limite_cero", nullable = false, precision = 53, scale = 0)
	public double getLimiteCero() {
		return this.limiteCero;
	}

	public void setLimiteCero(double limiteCero) {
		this.limiteCero = limiteCero;
	}

	@Column(name = "moneda_local", nullable = false)
	public Boolean getMonedaLocal() {
		return this.monedaLocal;
	}

	public void setMonedaLocal(Boolean monedaLocal) {
		this.monedaLocal = monedaLocal;
	}

	@Column(name = "codigo_camara", nullable = false, length = 10)
	public String getCodigoCamara() {
		return this.codigoCamara;
	}

	public void setCodigoCamara(String codigoCamara) {
		this.codigoCamara = codigoCamara;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moneda")
	public Set<DenominacionMoneda> getDenominacionMonedas() {
		return this.denominacionMonedas;
	}

	public void setDenominacionMonedas(Set<DenominacionMoneda> denominacionMonedas) {
		this.denominacionMonedas = denominacionMonedas;
	}

}
