package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notificacion generated by hbm2java
 */
@Entity
@Table(name = "notificacion", schema = "comun", catalog = "siisspolweb")
public class Notificacion implements java.io.Serializable {

	private Integer idNotificacion;
	private TipoNotificacion tipoNotificacion;
	private String propietario;
	private Date fecha;
	private Boolean revisado;
	private Boolean activo;
	private Date fechaVenc;
	private Date fechaBaja;
	private String referencia;
	private Date fechaRevision;
	private String mensaje;
	private Integer numNotificado;
	private String usuario;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public Notificacion() {
	}

	public Notificacion(Integer idNotificacion, TipoNotificacion tipoNotificacion, String propietario, Date fecha,
			Boolean revisado, Boolean activo, Date fechaVenc, String mensaje, Integer numNotificado, String usuario,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo) {
		this.idNotificacion = idNotificacion;
		this.tipoNotificacion = tipoNotificacion;
		this.propietario = propietario;
		this.fecha = fecha;
		this.revisado = revisado;
		this.activo = activo;
		this.fechaVenc = fechaVenc;
		this.mensaje = mensaje;
		this.numNotificado = numNotificado;
		this.usuario = usuario;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Notificacion(Integer idNotificacion, TipoNotificacion tipoNotificacion, String propietario, Date fecha,
			Boolean revisado, Boolean activo, Date fechaVenc, Date fechaBaja, String referencia, Date fechaRevision,
			String mensaje, Integer numNotificado, String usuario, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idNotificacion = idNotificacion;
		this.tipoNotificacion = tipoNotificacion;
		this.propietario = propietario;
		this.fecha = fecha;
		this.revisado = revisado;
		this.activo = activo;
		this.fechaVenc = fechaVenc;
		this.fechaBaja = fechaBaja;
		this.referencia = referencia;
		this.fechaRevision = fechaRevision;
		this.mensaje = mensaje;
		this.numNotificado = numNotificado;
		this.usuario = usuario;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_notificacion", unique = true, nullable = false)
	public Integer getIdNotificacion() {
		return this.idNotificacion;
	}

	public void setIdNotificacion(Integer idNotificacion) {
		this.idNotificacion = idNotificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_notificacion", nullable = false)
	public TipoNotificacion getTipoNotificacion() {
		return this.tipoNotificacion;
	}

	public void setTipoNotificacion(TipoNotificacion tipoNotificacion) {
		this.tipoNotificacion = tipoNotificacion;
	}

	@Column(name = "propietario", nullable = false, length = 15)
	public String getPropietario() {
		return this.propietario;
	}

	public void setPropietario(String propietario) {
		this.propietario = propietario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 23)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "revisado", nullable = false)
	public Boolean getRevisado() {
		return this.revisado;
	}

	public void setRevisado(Boolean revisado) {
		this.revisado = revisado;
	}

	@Column(name = "activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_venc", nullable = false, length = 23)
	public Date getFechaVenc() {
		return this.fechaVenc;
	}

	public void setFechaVenc(Date fechaVenc) {
		this.fechaVenc = fechaVenc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_baja", length = 23)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@Column(name = "referencia", length = 50)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_revision", length = 23)
	public Date getFechaRevision() {
		return this.fechaRevision;
	}

	public void setFechaRevision(Date fechaRevision) {
		this.fechaRevision = fechaRevision;
	}

	@Column(name = "mensaje", nullable = false, length = 100)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	@Column(name = "num_notificado", nullable = false)
	public Integer getNumNotificado() {
		return this.numNotificado;
	}

	public void setNumNotificado(Integer numNotificado) {
		this.numNotificado = numNotificado;
	}

	@Column(name = "usuario", nullable = false, length = 15)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
