package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import ec.org.isspol.persistence.entities.persona.VidaInstitucional;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Novedad generated by hbm2java
 */
@Entity
@Table(name = "novedad", schema = "comun", catalog = "siisspolweb")
public class Novedad implements java.io.Serializable {

	private Integer idNovedad;
	private String descripcion1;
	private String descripcion2;
	private String descripcion3;
	private String descripcion4;
	private BigDecimal numerico1;
	private BigDecimal numerico2;
	private BigDecimal numerico3;
	private BigDecimal numerico4;
	private BigDecimal numerico5;
	private Integer numerico6;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public Novedad() {
	}

	public Novedad(Integer idNovedad) {
		this.idNovedad = idNovedad;
	}

	public Novedad(Integer idNovedad, String descripcion1, String descripcion2, String descripcion3,
			String descripcion4, BigDecimal numerico1, BigDecimal numerico2, BigDecimal numerico3, BigDecimal numerico4,
			BigDecimal numerico5, Integer numerico6, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idNovedad = idNovedad;
		this.descripcion1 = descripcion1;
		this.descripcion2 = descripcion2;
		this.descripcion3 = descripcion3;
		this.descripcion4 = descripcion4;
		this.numerico1 = numerico1;
		this.numerico2 = numerico2;
		this.numerico3 = numerico3;
		this.numerico4 = numerico4;
		this.numerico5 = numerico5;
		this.numerico6 = numerico6;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_novedad", unique = true, nullable = false)
	public Integer getIdNovedad() {
		return this.idNovedad;
	}

	public void setIdNovedad(Integer idNovedad) {
		this.idNovedad = idNovedad;
	}

	@Column(name = "descripcion1", length = 60)
	public String getDescripcion1() {
		return this.descripcion1;
	}

	public void setDescripcion1(String descripcion1) {
		this.descripcion1 = descripcion1;
	}

	@Column(name = "descripcion2", length = 50)
	public String getDescripcion2() {
		return this.descripcion2;
	}

	public void setDescripcion2(String descripcion2) {
		this.descripcion2 = descripcion2;
	}

	@Column(name = "descripcion3", length = 50)
	public String getDescripcion3() {
		return this.descripcion3;
	}

	public void setDescripcion3(String descripcion3) {
		this.descripcion3 = descripcion3;
	}

	@Column(name = "descripcion4", length = 50)
	public String getDescripcion4() {
		return this.descripcion4;
	}

	public void setDescripcion4(String descripcion4) {
		this.descripcion4 = descripcion4;
	}

	@Column(name = "numerico1", precision = 18, scale = 0)
	public BigDecimal getNumerico1() {
		return this.numerico1;
	}

	public void setNumerico1(BigDecimal numerico1) {
		this.numerico1 = numerico1;
	}

	@Column(name = "numerico2", precision = 18, scale = 0)
	public BigDecimal getNumerico2() {
		return this.numerico2;
	}

	public void setNumerico2(BigDecimal numerico2) {
		this.numerico2 = numerico2;
	}

	@Column(name = "numerico3", precision = 18, scale = 0)
	public BigDecimal getNumerico3() {
		return this.numerico3;
	}

	public void setNumerico3(BigDecimal numerico3) {
		this.numerico3 = numerico3;
	}

	@Column(name = "numerico4", precision = 18, scale = 0)
	public BigDecimal getNumerico4() {
		return this.numerico4;
	}

	public void setNumerico4(BigDecimal numerico4) {
		this.numerico4 = numerico4;
	}

	@Column(name = "numerico5", precision = 18, scale = 0)
	public BigDecimal getNumerico5() {
		return this.numerico5;
	}

	public void setNumerico5(BigDecimal numerico5) {
		this.numerico5 = numerico5;
	}

	@Column(name = "numerico6")
	public Integer getNumerico6() {
		return this.numerico6;
	}

	public void setNumerico6(Integer numerico6) {
		this.numerico6 = numerico6;
	}

	@Column(name = "creacion_usuario", length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
