package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", schema = "comun", catalog = "siisspolweb")
public class Pais implements java.io.Serializable {

	private Integer idPais;
	private Integer isoNumerico;
	private String codigoIso2;
	private String codigoIso3;
	private String nombre;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<Region> regions = new HashSet<Region>(0);
	private Set<Nacionalidad> nacionalidads = new HashSet<Nacionalidad>(0);

	public Pais() {
	}

	public Pais(Integer idPais, Integer isoNumerico, String codigoIso2, String codigoIso3, String nombre) {
		this.idPais = idPais;
		this.isoNumerico = isoNumerico;
		this.codigoIso2 = codigoIso2;
		this.codigoIso3 = codigoIso3;
		this.nombre = nombre;
	}

	public Pais(Integer idPais, Integer isoNumerico, String codigoIso2, String codigoIso3, String nombre,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo, Set<Region> regions, Set<Nacionalidad> nacionalidads) {
		this.idPais = idPais;
		this.isoNumerico = isoNumerico;
		this.codigoIso2 = codigoIso2;
		this.codigoIso3 = codigoIso3;
		this.nombre = nombre;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.regions = regions;
		this.nacionalidads = nacionalidads;
	}

	@Id

	@Column(name = "id_pais", unique = true, nullable = false)
	public Integer getIdPais() {
		return this.idPais;
	}

	public void setIdPais(Integer idPais) {
		this.idPais = idPais;
	}

	@Column(name = "iso_numerico", nullable = false)
	public Integer getIsoNumerico() {
		return this.isoNumerico;
	}

	public void setIsoNumerico(Integer isoNumerico) {
		this.isoNumerico = isoNumerico;
	}

	@Column(name = "codigo_iso2", nullable = false, length = 2)
	public String getCodigoIso2() {
		return this.codigoIso2;
	}

	public void setCodigoIso2(String codigoIso2) {
		this.codigoIso2 = codigoIso2;
	}

	@Column(name = "codigo_iso3", nullable = false, length = 3)
	public String getCodigoIso3() {
		return this.codigoIso3;
	}

	public void setCodigoIso3(String codigoIso3) {
		this.codigoIso3 = codigoIso3;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "creacion_usuario", length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Region> getRegions() {
		return this.regions;
	}

	public void setRegions(Set<Region> regions) {
		this.regions = regions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Nacionalidad> getNacionalidads() {
		return this.nacionalidads;
	}

	public void setNacionalidads(Set<Nacionalidad> nacionalidads) {
		this.nacionalidads = nacionalidads;
	}

}
