package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parametro generated by hbm2java
 */
@Entity
@Table(name = "parametro", schema = "comun", catalog = "siisspolweb")
public class Parametro implements java.io.Serializable {

	private String parametro;
	private GrupoPar grupoPar;
	private String modulo;
	private String descripcion;
	private char tipoDato;
	private String valorS;
	private Date valorDt;
	private Integer valorI;
	private Double valorF;
	private Boolean valorB;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public Parametro() {
	}

	public Parametro(String parametro, String descripcion, char tipoDato, Boolean valorB, String creacionUsuario,
			Date creacionFecha, String creacionEquipo, String modificaUsuario, Date modificaFecha,
			String modificaEquipo) {
		this.parametro = parametro;
		this.descripcion = descripcion;
		this.tipoDato = tipoDato;
		this.valorB = valorB;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Parametro(String parametro, GrupoPar grupoPar, String modulo, String descripcion, char tipoDato,
			String valorS, Date valorDt, Integer valorI, Double valorF, Boolean valorB, String creacionUsuario,
			Date creacionFecha, String creacionEquipo, String modificaUsuario, Date modificaFecha,
			String modificaEquipo) {
		this.parametro = parametro;
		this.grupoPar = grupoPar;
		this.modulo = modulo;
		this.descripcion = descripcion;
		this.tipoDato = tipoDato;
		this.valorS = valorS;
		this.valorDt = valorDt;
		this.valorI = valorI;
		this.valorF = valorF;
		this.valorB = valorB;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id
	@Column(name = "parametro", unique = true, nullable = false, length = 20)
	public String getParametro() {
		return this.parametro;
	}

	public void setParametro(String parametro) {
		this.parametro = parametro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grupo_par")
	public GrupoPar getGrupoPar() {
		return this.grupoPar;
	}

	public void setGrupoPar(GrupoPar grupoPar) {
		this.grupoPar = grupoPar;
	}

	@Column(name = "modulo", length = 2)
	public String getModulo() {
		return this.modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "tipo_dato", nullable = false, length = 1)
	public char getTipoDato() {
		return this.tipoDato;
	}

	public void setTipoDato(char tipoDato) {
		this.tipoDato = tipoDato;
	}

	@Column(name = "valor_s")
	public String getValorS() {
		return this.valorS;
	}

	public void setValorS(String valorS) {
		this.valorS = valorS;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valor_dt", length = 23)
	public Date getValorDt() {
		return this.valorDt;
	}

	public void setValorDt(Date valorDt) {
		this.valorDt = valorDt;
	}

	@Column(name = "valor_i")
	public Integer getValorI() {
		return this.valorI;
	}

	public void setValorI(Integer valorI) {
		this.valorI = valorI;
	}

	@Column(name = "valor_f", precision = 53, scale = 0)
	public Double getValorF() {
		return this.valorF;
	}

	public void setValorF(Double valorF) {
		this.valorF = valorF;
	}

	@Column(name = "valor_b", nullable = false)
	public Boolean getValorB() {
		return this.valorB;
	}

	public void setValorB(Boolean valorB) {
		this.valorB = valorB;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
