package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SistemaAmbienteId generated by hbm2java
 */
@Embeddable
public class SistemaAmbienteId implements java.io.Serializable {

	private String ambiente;
	private String sistema;

	public SistemaAmbienteId() {
	}

	public SistemaAmbienteId(String ambiente, String sistema) {
		this.ambiente = ambiente;
		this.sistema = sistema;
	}

	@Column(name = "ambiente", nullable = false, length = 2)
	public String getAmbiente() {
		return this.ambiente;
	}

	public void setAmbiente(String ambiente) {
		this.ambiente = ambiente;
	}

	@Column(name = "sistema", nullable = false, length = 2)
	public String getSistema() {
		return this.sistema;
	}

	public void setSistema(String sistema) {
		this.sistema = sistema;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SistemaAmbienteId))
			return false;
		SistemaAmbienteId castOther = (SistemaAmbienteId) other;

		return ((this.getAmbiente() == castOther.getAmbiente()) || (this.getAmbiente() != null
				&& castOther.getAmbiente() != null && this.getAmbiente().equals(castOther.getAmbiente())))
				&& ((this.getSistema() == castOther.getSistema()) || (this.getSistema() != null
						&& castOther.getSistema() != null && this.getSistema().equals(castOther.getSistema())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAmbiente() == null ? 0 : this.getAmbiente().hashCode());
		result = 37 * result + (getSistema() == null ? 0 : this.getSistema().hashCode());
		return result;
	}

}
