package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoUbicacionGeografica generated by hbm2java
 */
@Entity
@Table(name = "tipo_ubicacion_geografica", schema = "comun", catalog = "siisspolweb")
public class TipoUbicacionGeografica implements java.io.Serializable {

	private Integer idTipoUbicacionGeografica;
	private String nombre;
	private String codigo;
	private Integer icono;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<UbicacionGeografica> ubicacionGeograficas = new HashSet<UbicacionGeografica>(0);

	public TipoUbicacionGeografica() {
	}

	public TipoUbicacionGeografica(Integer idTipoUbicacionGeografica, String nombre, String codigo, Integer icono,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo) {
		this.idTipoUbicacionGeografica = idTipoUbicacionGeografica;
		this.nombre = nombre;
		this.codigo = codigo;
		this.icono = icono;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public TipoUbicacionGeografica(Integer idTipoUbicacionGeografica, String nombre, String codigo, Integer icono,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo, Set<UbicacionGeografica> ubicacionGeograficas) {
		this.idTipoUbicacionGeografica = idTipoUbicacionGeografica;
		this.nombre = nombre;
		this.codigo = codigo;
		this.icono = icono;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.ubicacionGeograficas = ubicacionGeograficas;
	}

	@Id

	@Column(name = "id_tipo_ubicacion_geografica", unique = true, nullable = false)
	public Integer getIdTipoUbicacionGeografica() {
		return this.idTipoUbicacionGeografica;
	}

	public void setIdTipoUbicacionGeografica(Integer idTipoUbicacionGeografica) {
		this.idTipoUbicacionGeografica = idTipoUbicacionGeografica;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codigo", nullable = false, length = 2)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "icono", nullable = false)
	public Integer getIcono() {
		return this.icono;
	}

	public void setIcono(Integer icono) {
		this.icono = icono;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUbicacionGeografica")
	public Set<UbicacionGeografica> getUbicacionGeograficas() {
		return this.ubicacionGeograficas;
	}

	public void setUbicacionGeograficas(Set<UbicacionGeografica> ubicacionGeograficas) {
		this.ubicacionGeograficas = ubicacionGeograficas;
	}

}
