package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoNotificacion generated by hbm2java
 */
@Entity
@Table(name = "tipo_notificacion", schema = "comun", catalog = "siisspolweb")
public class TipoNotificacion implements java.io.Serializable {

	private String tipoNotificacion;
	private String descripcion;
	private Integer icono;
	private Integer tiempoExpiracion;
	private Integer numVezNotificado;
	private char tipo;
	private String opcion;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<Notificacion> notificacions = new HashSet<Notificacion>(0);

	public TipoNotificacion() {
	}

	public TipoNotificacion(String tipoNotificacion, String descripcion, Integer icono, Integer tiempoExpiracion,
			Integer numVezNotificado, char tipo, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.tipoNotificacion = tipoNotificacion;
		this.descripcion = descripcion;
		this.icono = icono;
		this.tiempoExpiracion = tiempoExpiracion;
		this.numVezNotificado = numVezNotificado;
		this.tipo = tipo;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public TipoNotificacion(String tipoNotificacion, String descripcion, Integer icono, Integer tiempoExpiracion,
			Integer numVezNotificado, char tipo, String opcion, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo,
			Set<Notificacion> notificacions) {
		this.tipoNotificacion = tipoNotificacion;
		this.descripcion = descripcion;
		this.icono = icono;
		this.tiempoExpiracion = tiempoExpiracion;
		this.numVezNotificado = numVezNotificado;
		this.tipo = tipo;
		this.opcion = opcion;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.notificacions = notificacions;
	}

	@Id

	@Column(name = "tipo_notificacion", unique = true, nullable = false, length = 5)
	public String getTipoNotificacion() {
		return this.tipoNotificacion;
	}

	public void setTipoNotificacion(String tipoNotificacion) {
		this.tipoNotificacion = tipoNotificacion;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "icono", nullable = false)
	public Integer getIcono() {
		return this.icono;
	}

	public void setIcono(Integer icono) {
		this.icono = icono;
	}

	@Column(name = "tiempo_expiracion", nullable = false)
	public Integer getTiempoExpiracion() {
		return this.tiempoExpiracion;
	}

	public void setTiempoExpiracion(Integer tiempoExpiracion) {
		this.tiempoExpiracion = tiempoExpiracion;
	}

	@Column(name = "num_vez_notificado", nullable = false)
	public Integer getNumVezNotificado() {
		return this.numVezNotificado;
	}

	public void setNumVezNotificado(Integer numVezNotificado) {
		this.numVezNotificado = numVezNotificado;
	}

	@Column(name = "tipo", nullable = false, length = 1)
	public char getTipo() {
		return this.tipo;
	}

	public void setTipo(char tipo) {
		this.tipo = tipo;
	}

	@Column(name = "opcion", length = 50)
	public String getOpcion() {
		return this.opcion;
	}

	public void setOpcion(String opcion) {
		this.opcion = opcion;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoNotificacion")
	public Set<Notificacion> getNotificacions() {
		return this.notificacions;
	}

	public void setNotificacions(Set<Notificacion> notificacions) {
		this.notificacions = notificacions;
	}

}
