package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UbicacionGeograficaMigracionId generated by hbm2java
 */
@Embeddable
public class UbicacionGeograficaMigracionId implements java.io.Serializable {

	private Integer tipoNivel;
	private Integer codOriginal;
	private Integer codUbicacion;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public UbicacionGeograficaMigracionId() {
	}

	public UbicacionGeograficaMigracionId(Integer tipoNivel, Integer codOriginal, Integer codUbicacion,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo) {
		this.tipoNivel = tipoNivel;
		this.codOriginal = codOriginal;
		this.codUbicacion = codUbicacion;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Column(name = "tipo_nivel", nullable = false)
	public Integer getTipoNivel() {
		return this.tipoNivel;
	}

	public void setTipoNivel(Integer tipoNivel) {
		this.tipoNivel = tipoNivel;
	}

	@Column(name = "cod_original", nullable = false)
	public Integer getCodOriginal() {
		return this.codOriginal;
	}

	public void setCodOriginal(Integer codOriginal) {
		this.codOriginal = codOriginal;
	}

	@Column(name = "cod_ubicacion", nullable = false)
	public Integer getCodUbicacion() {
		return this.codUbicacion;
	}

	public void setCodUbicacion(Integer codUbicacion) {
		this.codUbicacion = codUbicacion;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UbicacionGeograficaMigracionId))
			return false;
		UbicacionGeograficaMigracionId castOther = (UbicacionGeograficaMigracionId) other;

		return ((this.getTipoNivel() == castOther.getTipoNivel()) || (this.getTipoNivel() != null
				&& castOther.getTipoNivel() != null && this.getTipoNivel().equals(castOther.getTipoNivel())))
				&& ((this.getCodOriginal() == castOther.getCodOriginal())
						|| (this.getCodOriginal() != null && castOther.getCodOriginal() != null
								&& this.getCodOriginal().equals(castOther.getCodOriginal())))
				&& ((this.getCodUbicacion() == castOther.getCodUbicacion())
						|| (this.getCodUbicacion() != null && castOther.getCodUbicacion() != null
								&& this.getCodUbicacion().equals(castOther.getCodUbicacion())))
				&& ((this.getCreacionUsuario() == castOther.getCreacionUsuario())
						|| (this.getCreacionUsuario() != null && castOther.getCreacionUsuario() != null
								&& this.getCreacionUsuario().equals(castOther.getCreacionUsuario())))
				&& ((this.getCreacionFecha() == castOther.getCreacionFecha())
						|| (this.getCreacionFecha() != null && castOther.getCreacionFecha() != null
								&& this.getCreacionFecha().equals(castOther.getCreacionFecha())))
				&& ((this.getCreacionEquipo() == castOther.getCreacionEquipo())
						|| (this.getCreacionEquipo() != null && castOther.getCreacionEquipo() != null
								&& this.getCreacionEquipo().equals(castOther.getCreacionEquipo())))
				&& ((this.getModificaUsuario() == castOther.getModificaUsuario())
						|| (this.getModificaUsuario() != null && castOther.getModificaUsuario() != null
								&& this.getModificaUsuario().equals(castOther.getModificaUsuario())))
				&& ((this.getModificaFecha() == castOther.getModificaFecha())
						|| (this.getModificaFecha() != null && castOther.getModificaFecha() != null
								&& this.getModificaFecha().equals(castOther.getModificaFecha())))
				&& ((this.getModificaEquipo() == castOther.getModificaEquipo())
						|| (this.getModificaEquipo() != null && castOther.getModificaEquipo() != null
								&& this.getModificaEquipo().equals(castOther.getModificaEquipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTipoNivel() == null ? 0 : this.getTipoNivel().hashCode());
		result = 37 * result + (getCodOriginal() == null ? 0 : this.getCodOriginal().hashCode());
		result = 37 * result + (getCodUbicacion() == null ? 0 : this.getCodUbicacion().hashCode());
		result = 37 * result + (getCreacionUsuario() == null ? 0 : this.getCreacionUsuario().hashCode());
		result = 37 * result + (getCreacionFecha() == null ? 0 : this.getCreacionFecha().hashCode());
		result = 37 * result + (getCreacionEquipo() == null ? 0 : this.getCreacionEquipo().hashCode());
		result = 37 * result + (getModificaUsuario() == null ? 0 : this.getModificaUsuario().hashCode());
		result = 37 * result + (getModificaFecha() == null ? 0 : this.getModificaFecha().hashCode());
		result = 37 * result + (getModificaEquipo() == null ? 0 : this.getModificaEquipo().hashCode());
		return result;
	}

}
