package ec.org.isspol.persistence.entities.comun;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Version generated by hbm2java
 */
@Entity
@Table(name = "version", schema = "comun", catalog = "siisspolweb")
public class Version implements java.io.Serializable {

	private VersionId id;

	public Version() {
	}

	public Version(VersionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idVersion", column = @Column(name = "id_version", nullable = false)),
			@AttributeOverride(name = "etiqueta", column = @Column(name = "etiqueta", nullable = false, length = 10)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "descripcion", nullable = false, length = 150)),
			@AttributeOverride(name = "creacionUsuario", column = @Column(name = "creacion_usuario", nullable = false, length = 20)),
			@AttributeOverride(name = "creacionFecha", column = @Column(name = "creacion_fecha", nullable = false, length = 23)),
			@AttributeOverride(name = "creacionEquipo", column = @Column(name = "creacion_equipo", nullable = false, length = 20)),
			@AttributeOverride(name = "modificaUsuario", column = @Column(name = "modifica_usuario", nullable = false, length = 20)),
			@AttributeOverride(name = "modificaFecha", column = @Column(name = "modifica_fecha", nullable = false, length = 23)),
			@AttributeOverride(name = "modificaEquipo", column = @Column(name = "modifica_equipo", nullable = false, length = 20)) })
	public VersionId getId() {
		return this.id;
	}

	public void setId(VersionId id) {
		this.id = id;
	}

}
