USE [siisspolweb]
GO
/****** Object:  StoredProcedure [seguridad].[proc_validar_clave_fuerte]    Script Date: 27/04/2017 17:10:09 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [seguridad].[proc_validar_clave_fuerte]
@AS_USU_CLAVE VARCHAR(15),
@AS_MSJ varchar(100) OUTPUT
AS
DECLARE @MIN_MINUSCULA INT, @MIN_MAYUSCULA INT, @MIN_NUMERO INT, @MIN_SIMBOLO INT, 
		@LI_POSICION INT,
		@LS_PASSWORD  VARCHAR(15),
		@LI_CANT_LETRAS_MIN SMALLINT,
		@LI_CANT_LETRAS_MAY SMALLINT,
		@LI_CANT_NUMEROS SMALLINT,
		@CANT_ESPECIALES SMALLINT,
		@NUM_CARAC_TOTAL DECIMAL(9,2)
	SET @LS_PASSWORD  = @AS_USU_CLAVE
	SET @LI_POSICION = 1
	SET @LI_CANT_LETRAS_MIN = 0
	SET @LI_CANT_LETRAS_MAY = 0
	SET @LI_CANT_NUMEROS = 0
	SET @CANT_ESPECIALES = 0

	
	SELECT @MIN_MINUSCULA = ISNULL(minimo_minuscula,0), @MIN_MAYUSCULA = ISNULL(minimo_mayuscula,0), @MIN_NUMERO = ISNULL(minimo_numero,0),
	@MIN_SIMBOLO = ISNULL(minimo_simbolo,0)
	FROM seguridad.politica_clave where defecto = 1;

	WHILE @LI_POSICION <= DATALENGTH(@LS_PASSWORD )
	BEGIN
		IF ASCII(SUBSTRING(@LS_PASSWORD , @LI_POSICION, 1)) BETWEEN ASCII('a')AND ASCII('z')
		BEGIN
			SET @LI_CANT_LETRAS_MIN = @LI_CANT_LETRAS_MIN + 1
		END

		IF ASCII(SUBSTRING(@LS_PASSWORD , @LI_POSICION, 1)) BETWEEN ASCII('A')AND ASCII('Z')
		BEGIN
			SET @LI_CANT_LETRAS_MAY = @LI_CANT_LETRAS_MAY + 1
		END
		
		IF SUBSTRING(@LS_PASSWORD , @LI_POSICION, 1) LIKE '[0-9]'
		BEGIN
			SET @LI_CANT_NUMEROS = @LI_CANT_NUMEROS + 1
		END
		
		IF  SUBSTRING(@LS_PASSWORD , @LI_POSICION, 1) NOT LIKE '[0-9]' 
			AND SUBSTRING(@LS_PASSWORD , @LI_POSICION, 1) NOT LIKE '[a-z]' 
		BEGIN
			SET @CANT_ESPECIALES = @CANT_ESPECIALES + 1
		END
		SET @LI_POSICION = @LI_POSICION + 1
	END
	IF @LI_CANT_NUMEROS < @MIN_NUMERO
	BEGIN
			SET @AS_MSJ = 'LA CLAVE DEBE TENER AL MENOS '+ CONVERT  ( VARCHAR, @MIN_NUMERO) +' NUMERO(S)' 
				RETURN -1
	END
	IF @CANT_ESPECIALES < @MIN_SIMBOLO
	BEGIN
			SET @AS_MSJ = 'LA CLAVE DEBE TENER AL MENOS '+ CONVERT  ( VARCHAR, @MIN_SIMBOLO) +' CARACTERE(S) ESPECIALE(S)' 
				RETURN -1
	END
	IF @LI_CANT_LETRAS_MIN < @MIN_MINUSCULA
	BEGIN
			SET @AS_MSJ = 'LA CLAVE DEBE TENER AL MENOS '+ CONVERT  ( VARCHAR, @MIN_MINUSCULA) +' LETRA(S) MINISCULA(S)' 
				RETURN -1
	END
	IF @LI_CANT_LETRAS_MAY < @MIN_MAYUSCULA
	BEGIN
			SET @AS_MSJ = 'LA CLAVE DEBE TENER AL MENOS '+ CONVERT  ( VARCHAR, @MIN_MAYUSCULA) +' LETRA(S) MAYUSCULA(S)' 
				RETURN -1
	END
RETURN 1
/***********************************************************************************/
