package ec.org.isspol.persistence.entities.auditoria;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Columna generated by hbm2java
 */
@Entity
@Table(name = "columna", schema = "auditoria", catalog = "siisspolweb")
public class Columna implements java.io.Serializable {

	private Integer idColumna;
	private Tabla tabla;
	private String nombre;
	private String nombreBdd;
	private Boolean auditar;
	private Boolean clavePrimaria;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<RastroPk> rastroPks = new HashSet<RastroPk>(0);
	private Set<RastroDetalle> rastroDetalles = new HashSet<RastroDetalle>(0);

	public Columna() {
	}

	public Columna(Integer idColumna, Tabla tabla, String nombre, String nombreBdd, Boolean auditar,
			Boolean clavePrimaria, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idColumna = idColumna;
		this.tabla = tabla;
		this.nombre = nombre;
		this.nombreBdd = nombreBdd;
		this.auditar = auditar;
		this.clavePrimaria = clavePrimaria;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Columna(Integer idColumna, Tabla tabla, String nombre, String nombreBdd, Boolean auditar,
			Boolean clavePrimaria, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo, Set<RastroPk> rastroPks,
			Set<RastroDetalle> rastroDetalles) {
		this.idColumna = idColumna;
		this.tabla = tabla;
		this.nombre = nombre;
		this.nombreBdd = nombreBdd;
		this.auditar = auditar;
		this.clavePrimaria = clavePrimaria;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.rastroPks = rastroPks;
		this.rastroDetalles = rastroDetalles;
	}

	@Id

	@Column(name = "id_columna", unique = true, nullable = false)
	public Integer getIdColumna() {
		return this.idColumna;
	}

	public void setIdColumna(Integer idColumna) {
		this.idColumna = idColumna;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tabla", nullable = false)
	public Tabla getTabla() {
		return this.tabla;
	}

	public void setTabla(Tabla tabla) {
		this.tabla = tabla;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "nombre_bdd", nullable = false, length = 50)
	public String getNombreBdd() {
		return this.nombreBdd;
	}

	public void setNombreBdd(String nombreBdd) {
		this.nombreBdd = nombreBdd;
	}

	@Column(name = "auditar", nullable = false)
	public Boolean getAuditar() {
		return this.auditar;
	}

	public void setAuditar(Boolean auditar) {
		this.auditar = auditar;
	}

	@Column(name = "clave_primaria", nullable = false)
	public Boolean getClavePrimaria() {
		return this.clavePrimaria;
	}

	public void setClavePrimaria(Boolean clavePrimaria) {
		this.clavePrimaria = clavePrimaria;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "columna")
	public Set<RastroPk> getRastroPks() {
		return this.rastroPks;
	}

	public void setRastroPks(Set<RastroPk> rastroPks) {
		this.rastroPks = rastroPks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "columna")
	public Set<RastroDetalle> getRastroDetalles() {
		return this.rastroDetalles;
	}

	public void setRastroDetalles(Set<RastroDetalle> rastroDetalles) {
		this.rastroDetalles = rastroDetalles;
	}

}
