package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Carpeta generated by hbm2java
 */
@Entity
@Table(name = "carpeta", schema = "persona", catalog = "siisspolweb")
public class Carpeta implements java.io.Serializable {

	private Integer idCarpeta;
	private Departamento departamentoByIdDepartamentoOrigen;
	private Persona persona;
	private Departamento departamentoByIdDepartamentoDestino;
	private TipoTramite tipoTramite;
	private Date fecha;
	private Integer numero;
	private Integer secuencia;
	private Integer idUsuarioOrigen;
	private Boolean habilitado;
	private String observacion;
	private Integer idUsuarioRecibe;
	private Date fechaRecibe;
	private Boolean estadoDevolucion;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public Carpeta() {
	}

	public Carpeta(Integer idCarpeta, Departamento departamentoByIdDepartamentoOrigen, Persona persona,
			Departamento departamentoByIdDepartamentoDestino, TipoTramite tipoTramite, Date fecha, Integer numero,
			Integer secuencia, Integer idUsuarioOrigen, Boolean habilitado, String observacion, Integer idUsuarioRecibe,
			Date fechaRecibe, Boolean estadoDevolucion, Boolean eliminado, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idCarpeta = idCarpeta;
		this.departamentoByIdDepartamentoOrigen = departamentoByIdDepartamentoOrigen;
		this.persona = persona;
		this.departamentoByIdDepartamentoDestino = departamentoByIdDepartamentoDestino;
		this.tipoTramite = tipoTramite;
		this.fecha = fecha;
		this.numero = numero;
		this.secuencia = secuencia;
		this.idUsuarioOrigen = idUsuarioOrigen;
		this.habilitado = habilitado;
		this.observacion = observacion;
		this.idUsuarioRecibe = idUsuarioRecibe;
		this.fechaRecibe = fechaRecibe;
		this.estadoDevolucion = estadoDevolucion;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_carpeta", unique = true, nullable = false)
	public Integer getIdCarpeta() {
		return this.idCarpeta;
	}

	public void setIdCarpeta(Integer idCarpeta) {
		this.idCarpeta = idCarpeta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_departamento_origen", nullable = false)
	public Departamento getDepartamentoByIdDepartamentoOrigen() {
		return this.departamentoByIdDepartamentoOrigen;
	}

	public void setDepartamentoByIdDepartamentoOrigen(Departamento departamentoByIdDepartamentoOrigen) {
		this.departamentoByIdDepartamentoOrigen = departamentoByIdDepartamentoOrigen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_departamento_destino", nullable = false)
	public Departamento getDepartamentoByIdDepartamentoDestino() {
		return this.departamentoByIdDepartamentoDestino;
	}

	public void setDepartamentoByIdDepartamentoDestino(Departamento departamentoByIdDepartamentoDestino) {
		this.departamentoByIdDepartamentoDestino = departamentoByIdDepartamentoDestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_tramite", nullable = false)
	public TipoTramite getTipoTramite() {
		return this.tipoTramite;
	}

	public void setTipoTramite(TipoTramite tipoTramite) {
		this.tipoTramite = tipoTramite;
	}

	@Column(name = "fecha", nullable = false, length = 23)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "numero", nullable = false)
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "secuencia", nullable = false)
	public Integer getSecuencia() {
		return this.secuencia;
	}

	public void setSecuencia(Integer secuencia) {
		this.secuencia = secuencia;
	}

	@Column(name = "id_usuario_origen", nullable = false)
	public Integer getIdUsuarioOrigen() {
		return this.idUsuarioOrigen;
	}

	public void setIdUsuarioOrigen(Integer idUsuarioOrigen) {
		this.idUsuarioOrigen = idUsuarioOrigen;
	}

	@Column(name = "habilitado", nullable = false)
	public Boolean getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Boolean habilitado) {
		this.habilitado = habilitado;
	}

	@Column(name = "observacion", nullable = false, length = 200)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "id_usuario_recibe", nullable = false)
	public Integer getIdUsuarioRecibe() {
		return this.idUsuarioRecibe;
	}

	public void setIdUsuarioRecibe(Integer idUsuarioRecibe) {
		this.idUsuarioRecibe = idUsuarioRecibe;
	}

	@Column(name = "fecha_recibe", nullable = false, length = 23)
	public Date getFechaRecibe() {
		return this.fechaRecibe;
	}

	public void setFechaRecibe(Date fechaRecibe) {
		this.fechaRecibe = fechaRecibe;
	}

	@Column(name = "estado_devolucion", nullable = false)
	public Boolean getEstadoDevolucion() {
		return this.estadoDevolucion;
	}

	public void setEstadoDevolucion(Boolean estadoDevolucion) {
		this.estadoDevolucion = estadoDevolucion;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
