package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CausantePension generated by hbm2java
 */
@Entity
@Table(name = "causante_pension", schema = "persona", catalog = "siisspolweb")
public class CausantePension implements java.io.Serializable {

	private Integer idCausantePension;
	private Invalides invalides;
	private OrigenDiscapacidad origenDiscapacidad;
	private Grado grado;
	private PersonaTipoSubtipo personaTipoSubtipo;
	private String expediente;
	private Integer idTipoDiscapacidad;
	private String tiempoCadeteCivil;
	private String tiempoCadetePlanta;
	private String tiempoCadetePolicial;
	private String tiempoCadeteTotal;
	private String tiempoTropa;
	private String tiempoOficial;
	private String tiempoCivil;
	private String tiempoMilitar;
	private String tiempoEfectivo;
	private String tiempoTotal;
	private String tiempoCadeteHabilitado;
	private Integer baseCalculo;
	private Integer porcentajeCoeficienteCorrecion;
	private BigDecimal porcentajeRetiro;
	private String porcentajeNucleo;
	private BigDecimal pensionRetiro;
	private String pensionNucleo;
	private Boolean habilitado;
	private Date fechaLiquidacion;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<Montepio> montepios = new HashSet<Montepio>(0);

	public CausantePension() {
	}

	public CausantePension(Integer idCausantePension, Invalides invalides, OrigenDiscapacidad origenDiscapacidad,
			Grado grado, PersonaTipoSubtipo personaTipoSubtipo, String expediente, String tiempoCadeteCivil,
			String tiempoCadetePlanta, String tiempoCadetePolicial, String tiempoCadeteTotal, String tiempoTropa,
			String tiempoOficial, String tiempoCivil, String tiempoMilitar, String tiempoEfectivo, String tiempoTotal,
			String tiempoCadeteHabilitado, BigDecimal porcentajeRetiro, String porcentajeNucleo,
			BigDecimal pensionRetiro, String pensionNucleo, Boolean habilitado, Date fechaLiquidacion,
			Boolean eliminado, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idCausantePension = idCausantePension;
		this.invalides = invalides;
		this.origenDiscapacidad = origenDiscapacidad;
		this.grado = grado;
		this.personaTipoSubtipo = personaTipoSubtipo;
		this.expediente = expediente;
		this.tiempoCadeteCivil = tiempoCadeteCivil;
		this.tiempoCadetePlanta = tiempoCadetePlanta;
		this.tiempoCadetePolicial = tiempoCadetePolicial;
		this.tiempoCadeteTotal = tiempoCadeteTotal;
		this.tiempoTropa = tiempoTropa;
		this.tiempoOficial = tiempoOficial;
		this.tiempoCivil = tiempoCivil;
		this.tiempoMilitar = tiempoMilitar;
		this.tiempoEfectivo = tiempoEfectivo;
		this.tiempoTotal = tiempoTotal;
		this.tiempoCadeteHabilitado = tiempoCadeteHabilitado;
		this.porcentajeRetiro = porcentajeRetiro;
		this.porcentajeNucleo = porcentajeNucleo;
		this.pensionRetiro = pensionRetiro;
		this.pensionNucleo = pensionNucleo;
		this.habilitado = habilitado;
		this.fechaLiquidacion = fechaLiquidacion;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public CausantePension(Integer idCausantePension, Invalides invalides, OrigenDiscapacidad origenDiscapacidad,
			Grado grado, PersonaTipoSubtipo personaTipoSubtipo, String expediente, Integer idTipoDiscapacidad,
			String tiempoCadeteCivil, String tiempoCadetePlanta, String tiempoCadetePolicial, String tiempoCadeteTotal,
			String tiempoTropa, String tiempoOficial, String tiempoCivil, String tiempoMilitar, String tiempoEfectivo,
			String tiempoTotal, String tiempoCadeteHabilitado, Integer baseCalculo,
			Integer porcentajeCoeficienteCorrecion, BigDecimal porcentajeRetiro, String porcentajeNucleo,
			BigDecimal pensionRetiro, String pensionNucleo, Boolean habilitado, Date fechaLiquidacion,
			Boolean eliminado, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo, Set<Montepio> montepios) {
		this.idCausantePension = idCausantePension;
		this.invalides = invalides;
		this.origenDiscapacidad = origenDiscapacidad;
		this.grado = grado;
		this.personaTipoSubtipo = personaTipoSubtipo;
		this.expediente = expediente;
		this.idTipoDiscapacidad = idTipoDiscapacidad;
		this.tiempoCadeteCivil = tiempoCadeteCivil;
		this.tiempoCadetePlanta = tiempoCadetePlanta;
		this.tiempoCadetePolicial = tiempoCadetePolicial;
		this.tiempoCadeteTotal = tiempoCadeteTotal;
		this.tiempoTropa = tiempoTropa;
		this.tiempoOficial = tiempoOficial;
		this.tiempoCivil = tiempoCivil;
		this.tiempoMilitar = tiempoMilitar;
		this.tiempoEfectivo = tiempoEfectivo;
		this.tiempoTotal = tiempoTotal;
		this.tiempoCadeteHabilitado = tiempoCadeteHabilitado;
		this.baseCalculo = baseCalculo;
		this.porcentajeCoeficienteCorrecion = porcentajeCoeficienteCorrecion;
		this.porcentajeRetiro = porcentajeRetiro;
		this.porcentajeNucleo = porcentajeNucleo;
		this.pensionRetiro = pensionRetiro;
		this.pensionNucleo = pensionNucleo;
		this.habilitado = habilitado;
		this.fechaLiquidacion = fechaLiquidacion;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.montepios = montepios;
	}

	@Id

	@Column(name = "id_causante_pension", unique = true, nullable = false)
	public Integer getIdCausantePension() {
		return this.idCausantePension;
	}

	public void setIdCausantePension(Integer idCausantePension) {
		this.idCausantePension = idCausantePension;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_origen_discapacidad", nullable = false)
	public Invalides getInvalides() {
		return this.invalides;
	}

	public void setInvalides(Invalides invalides) {
		this.invalides = invalides;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_origen_discapacidad", nullable = false, insertable = false, updatable = false)
	public OrigenDiscapacidad getOrigenDiscapacidad() {
		return this.origenDiscapacidad;
	}

	public void setOrigenDiscapacidad(OrigenDiscapacidad origenDiscapacidad) {
		this.origenDiscapacidad = origenDiscapacidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grado_sueldo", nullable = false)
	public Grado getGrado() {
		return this.grado;
	}

	public void setGrado(Grado grado) {
		this.grado = grado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_tipo_subtipo", nullable = false)
	public PersonaTipoSubtipo getPersonaTipoSubtipo() {
		return this.personaTipoSubtipo;
	}

	public void setPersonaTipoSubtipo(PersonaTipoSubtipo personaTipoSubtipo) {
		this.personaTipoSubtipo = personaTipoSubtipo;
	}

	@Column(name = "expediente", nullable = false, length = 6)
	public String getExpediente() {
		return this.expediente;
	}

	public void setExpediente(String expediente) {
		this.expediente = expediente;
	}

	@Column(name = "id_tipo_discapacidad")
	public Integer getIdTipoDiscapacidad() {
		return this.idTipoDiscapacidad;
	}

	public void setIdTipoDiscapacidad(Integer idTipoDiscapacidad) {
		this.idTipoDiscapacidad = idTipoDiscapacidad;
	}

	@Column(name = "tiempo_cadete_civil", nullable = false, length = 8)
	public String getTiempoCadeteCivil() {
		return this.tiempoCadeteCivil;
	}

	public void setTiempoCadeteCivil(String tiempoCadeteCivil) {
		this.tiempoCadeteCivil = tiempoCadeteCivil;
	}

	@Column(name = "tiempo_cadete_planta", nullable = false, length = 8)
	public String getTiempoCadetePlanta() {
		return this.tiempoCadetePlanta;
	}

	public void setTiempoCadetePlanta(String tiempoCadetePlanta) {
		this.tiempoCadetePlanta = tiempoCadetePlanta;
	}

	@Column(name = "tiempo_cadete_policial", nullable = false, length = 8)
	public String getTiempoCadetePolicial() {
		return this.tiempoCadetePolicial;
	}

	public void setTiempoCadetePolicial(String tiempoCadetePolicial) {
		this.tiempoCadetePolicial = tiempoCadetePolicial;
	}

	@Column(name = "tiempo_cadete_total", nullable = false, length = 8)
	public String getTiempoCadeteTotal() {
		return this.tiempoCadeteTotal;
	}

	public void setTiempoCadeteTotal(String tiempoCadeteTotal) {
		this.tiempoCadeteTotal = tiempoCadeteTotal;
	}

	@Column(name = "tiempo_tropa", nullable = false, length = 8)
	public String getTiempoTropa() {
		return this.tiempoTropa;
	}

	public void setTiempoTropa(String tiempoTropa) {
		this.tiempoTropa = tiempoTropa;
	}

	@Column(name = "tiempo_oficial", nullable = false, length = 8)
	public String getTiempoOficial() {
		return this.tiempoOficial;
	}

	public void setTiempoOficial(String tiempoOficial) {
		this.tiempoOficial = tiempoOficial;
	}

	@Column(name = "tiempo_civil", nullable = false, length = 8)
	public String getTiempoCivil() {
		return this.tiempoCivil;
	}

	public void setTiempoCivil(String tiempoCivil) {
		this.tiempoCivil = tiempoCivil;
	}

	@Column(name = "tiempo_militar", nullable = false, length = 8)
	public String getTiempoMilitar() {
		return this.tiempoMilitar;
	}

	public void setTiempoMilitar(String tiempoMilitar) {
		this.tiempoMilitar = tiempoMilitar;
	}

	@Column(name = "tiempo_efectivo", nullable = false, length = 8)
	public String getTiempoEfectivo() {
		return this.tiempoEfectivo;
	}

	public void setTiempoEfectivo(String tiempoEfectivo) {
		this.tiempoEfectivo = tiempoEfectivo;
	}

	@Column(name = "tiempo_total", nullable = false, length = 8)
	public String getTiempoTotal() {
		return this.tiempoTotal;
	}

	public void setTiempoTotal(String tiempoTotal) {
		this.tiempoTotal = tiempoTotal;
	}

	@Column(name = "tiempo_cadete_habilitado", nullable = false, length = 8)
	public String getTiempoCadeteHabilitado() {
		return this.tiempoCadeteHabilitado;
	}

	public void setTiempoCadeteHabilitado(String tiempoCadeteHabilitado) {
		this.tiempoCadeteHabilitado = tiempoCadeteHabilitado;
	}

	@Column(name = "base_calculo")
	public Integer getBaseCalculo() {
		return this.baseCalculo;
	}

	public void setBaseCalculo(Integer baseCalculo) {
		this.baseCalculo = baseCalculo;
	}

	@Column(name = "porcentaje_coeficiente_correcion")
	public Integer getPorcentajeCoeficienteCorrecion() {
		return this.porcentajeCoeficienteCorrecion;
	}

	public void setPorcentajeCoeficienteCorrecion(Integer porcentajeCoeficienteCorrecion) {
		this.porcentajeCoeficienteCorrecion = porcentajeCoeficienteCorrecion;
	}

	@Column(name = "porcentaje_retiro", nullable = false, scale = 4)
	public BigDecimal getPorcentajeRetiro() {
		return this.porcentajeRetiro;
	}

	public void setPorcentajeRetiro(BigDecimal porcentajeRetiro) {
		this.porcentajeRetiro = porcentajeRetiro;
	}

	@Column(name = "porcentaje_nucleo", nullable = false, length = 10)
	public String getPorcentajeNucleo() {
		return this.porcentajeNucleo;
	}

	public void setPorcentajeNucleo(String porcentajeNucleo) {
		this.porcentajeNucleo = porcentajeNucleo;
	}

	@Column(name = "pension_retiro", nullable = false, scale = 4)
	public BigDecimal getPensionRetiro() {
		return this.pensionRetiro;
	}

	public void setPensionRetiro(BigDecimal pensionRetiro) {
		this.pensionRetiro = pensionRetiro;
	}

	@Column(name = "pension_nucleo", nullable = false, length = 10)
	public String getPensionNucleo() {
		return this.pensionNucleo;
	}

	public void setPensionNucleo(String pensionNucleo) {
		this.pensionNucleo = pensionNucleo;
	}

	@Column(name = "habilitado", nullable = false)
	public Boolean getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Boolean habilitado) {
		this.habilitado = habilitado;
	}

	@Column(name = "fecha_liquidacion", nullable = false, length = 23)
	public Date getFechaLiquidacion() {
		return this.fechaLiquidacion;
	}

	public void setFechaLiquidacion(Date fechaLiquidacion) {
		this.fechaLiquidacion = fechaLiquidacion;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "causantePension")
	public Set<Montepio> getMontepios() {
		return this.montepios;
	}

	public void setMontepios(Set<Montepio> montepios) {
		this.montepios = montepios;
	}

}
