package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento", schema = "persona", catalog = "siisspolweb")
public class Departamento implements java.io.Serializable {

	private Integer idDepartamento;
	private String descripcion1;
	private String descripcion2;
	private BigDecimal numerico1;
	private BigDecimal numerico2;
	private BigDecimal numerico3;
	private Integer numerico4;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<Carpeta> carpetasForIdDepartamentoOrigen = new HashSet<Carpeta>(0);
	private Set<Carpeta> carpetasForIdDepartamentoDestino = new HashSet<Carpeta>(0);

	public Departamento() {
	}

	public Departamento(Integer idDepartamento, Boolean eliminado, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idDepartamento = idDepartamento;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Departamento(Integer idDepartamento, String descripcion1, String descripcion2, BigDecimal numerico1,
			BigDecimal numerico2, BigDecimal numerico3, Integer numerico4, Boolean eliminado, String creacionUsuario,
			Date creacionFecha, String creacionEquipo, String modificaUsuario, Date modificaFecha,
			String modificaEquipo, Set<Carpeta> carpetasForIdDepartamentoOrigen,
			Set<Carpeta> carpetasForIdDepartamentoDestino) {
		this.idDepartamento = idDepartamento;
		this.descripcion1 = descripcion1;
		this.descripcion2 = descripcion2;
		this.numerico1 = numerico1;
		this.numerico2 = numerico2;
		this.numerico3 = numerico3;
		this.numerico4 = numerico4;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.carpetasForIdDepartamentoOrigen = carpetasForIdDepartamentoOrigen;
		this.carpetasForIdDepartamentoDestino = carpetasForIdDepartamentoDestino;
	}

	@Id

	@Column(name = "id_departamento", unique = true, nullable = false)
	public Integer getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(Integer idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	@Column(name = "descripcion1", length = 60)
	public String getDescripcion1() {
		return this.descripcion1;
	}

	public void setDescripcion1(String descripcion1) {
		this.descripcion1 = descripcion1;
	}

	@Column(name = "descripcion2", length = 50)
	public String getDescripcion2() {
		return this.descripcion2;
	}

	public void setDescripcion2(String descripcion2) {
		this.descripcion2 = descripcion2;
	}

	@Column(name = "numerico1", precision = 18, scale = 0)
	public BigDecimal getNumerico1() {
		return this.numerico1;
	}

	public void setNumerico1(BigDecimal numerico1) {
		this.numerico1 = numerico1;
	}

	@Column(name = "numerico2", precision = 18, scale = 0)
	public BigDecimal getNumerico2() {
		return this.numerico2;
	}

	public void setNumerico2(BigDecimal numerico2) {
		this.numerico2 = numerico2;
	}

	@Column(name = "numerico3", precision = 18, scale = 0)
	public BigDecimal getNumerico3() {
		return this.numerico3;
	}

	public void setNumerico3(BigDecimal numerico3) {
		this.numerico3 = numerico3;
	}

	@Column(name = "numerico4")
	public Integer getNumerico4() {
		return this.numerico4;
	}

	public void setNumerico4(Integer numerico4) {
		this.numerico4 = numerico4;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamentoByIdDepartamentoOrigen")
	public Set<Carpeta> getCarpetasForIdDepartamentoOrigen() {
		return this.carpetasForIdDepartamentoOrigen;
	}

	public void setCarpetasForIdDepartamentoOrigen(Set<Carpeta> carpetasForIdDepartamentoOrigen) {
		this.carpetasForIdDepartamentoOrigen = carpetasForIdDepartamentoOrigen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamentoByIdDepartamentoDestino")
	public Set<Carpeta> getCarpetasForIdDepartamentoDestino() {
		return this.carpetasForIdDepartamentoDestino;
	}

	public void setCarpetasForIdDepartamentoDestino(Set<Carpeta> carpetasForIdDepartamentoDestino) {
		this.carpetasForIdDepartamentoDestino = carpetasForIdDepartamentoDestino;
	}

}
