package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dependiente generated by hbm2java
 */
@Entity
@Table(name = "dependiente", schema = "persona", catalog = "siisspolweb")
public class Dependiente implements java.io.Serializable {

	private Integer idDependiente;
	private OrigenDiscapacidad origenDiscapacidad;
	private Persona persona;
	private TipoDiscapacidad tipoDiscapacidad;
	private PersonaTipoSubtipo personaTipoSubtipoByIdPersonaTipoSubtipoCausante;
	private PersonaTipoSubtipo personaTipoSubtipoByIdPersonaTipoSubtipo;
	private Parentesco parentesco;
	private String enfermedadCatastrofica;
	private Boolean validado;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public Dependiente() {
	}

	public Dependiente(Integer idDependiente, OrigenDiscapacidad origenDiscapacidad, Persona persona,
			PersonaTipoSubtipo personaTipoSubtipoByIdPersonaTipoSubtipoCausante,
			PersonaTipoSubtipo personaTipoSubtipoByIdPersonaTipoSubtipo, Parentesco parentesco,
			String enfermedadCatastrofica, Boolean eliminado, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idDependiente = idDependiente;
		this.origenDiscapacidad = origenDiscapacidad;
		this.persona = persona;
		this.personaTipoSubtipoByIdPersonaTipoSubtipoCausante = personaTipoSubtipoByIdPersonaTipoSubtipoCausante;
		this.personaTipoSubtipoByIdPersonaTipoSubtipo = personaTipoSubtipoByIdPersonaTipoSubtipo;
		this.parentesco = parentesco;
		this.enfermedadCatastrofica = enfermedadCatastrofica;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Dependiente(Integer idDependiente, OrigenDiscapacidad origenDiscapacidad, Persona persona,
			TipoDiscapacidad tipoDiscapacidad, PersonaTipoSubtipo personaTipoSubtipoByIdPersonaTipoSubtipoCausante,
			PersonaTipoSubtipo personaTipoSubtipoByIdPersonaTipoSubtipo, Parentesco parentesco,
			String enfermedadCatastrofica, Boolean validado, Boolean eliminado, String creacionUsuario,
			Date creacionFecha, String creacionEquipo, String modificaUsuario, Date modificaFecha,
			String modificaEquipo) {
		this.idDependiente = idDependiente;
		this.origenDiscapacidad = origenDiscapacidad;
		this.persona = persona;
		this.tipoDiscapacidad = tipoDiscapacidad;
		this.personaTipoSubtipoByIdPersonaTipoSubtipoCausante = personaTipoSubtipoByIdPersonaTipoSubtipoCausante;
		this.personaTipoSubtipoByIdPersonaTipoSubtipo = personaTipoSubtipoByIdPersonaTipoSubtipo;
		this.parentesco = parentesco;
		this.enfermedadCatastrofica = enfermedadCatastrofica;
		this.validado = validado;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_dependiente", unique = true, nullable = false)
	public Integer getIdDependiente() {
		return this.idDependiente;
	}

	public void setIdDependiente(Integer idDependiente) {
		this.idDependiente = idDependiente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_origen_discapacidad", nullable = false)
	public OrigenDiscapacidad getOrigenDiscapacidad() {
		return this.origenDiscapacidad;
	}

	public void setOrigenDiscapacidad(OrigenDiscapacidad origenDiscapacidad) {
		this.origenDiscapacidad = origenDiscapacidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_tipo_subtipo", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_discapacidad")
	public TipoDiscapacidad getTipoDiscapacidad() {
		return this.tipoDiscapacidad;
	}

	public void setTipoDiscapacidad(TipoDiscapacidad tipoDiscapacidad) {
		this.tipoDiscapacidad = tipoDiscapacidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_tipo_subtipo_causante", nullable = false)
	public PersonaTipoSubtipo getPersonaTipoSubtipoByIdPersonaTipoSubtipoCausante() {
		return this.personaTipoSubtipoByIdPersonaTipoSubtipoCausante;
	}

	public void setPersonaTipoSubtipoByIdPersonaTipoSubtipoCausante(
			PersonaTipoSubtipo personaTipoSubtipoByIdPersonaTipoSubtipoCausante) {
		this.personaTipoSubtipoByIdPersonaTipoSubtipoCausante = personaTipoSubtipoByIdPersonaTipoSubtipoCausante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_tipo_subtipo", nullable = false, insertable = false, updatable = false)
	public PersonaTipoSubtipo getPersonaTipoSubtipoByIdPersonaTipoSubtipo() {
		return this.personaTipoSubtipoByIdPersonaTipoSubtipo;
	}

	public void setPersonaTipoSubtipoByIdPersonaTipoSubtipo(
			PersonaTipoSubtipo personaTipoSubtipoByIdPersonaTipoSubtipo) {
		this.personaTipoSubtipoByIdPersonaTipoSubtipo = personaTipoSubtipoByIdPersonaTipoSubtipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_parentesco", nullable = false)
	public Parentesco getParentesco() {
		return this.parentesco;
	}

	public void setParentesco(Parentesco parentesco) {
		this.parentesco = parentesco;
	}

	@Column(name = "enfermedad_catastrofica", nullable = false, length = 10)
	public String getEnfermedadCatastrofica() {
		return this.enfermedadCatastrofica;
	}

	public void setEnfermedadCatastrofica(String enfermedadCatastrofica) {
		this.enfermedadCatastrofica = enfermedadCatastrofica;
	}

	@Column(name = "validado")
	public Boolean getValidado() {
		return this.validado;
	}

	public void setValidado(Boolean validado) {
		this.validado = validado;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
