package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "direccion", schema = "persona", catalog = "siisspolweb")
public class Direccion implements java.io.Serializable {

	private Integer idDireccion;
	private Persona persona;
	private Integer idUbicacionGeografica;
	private String callePrincipal;
	private String calleSecundaria;
	private String numeroCasa;
	private String telefonoUno;
	private String telefonoDos;
	private String celular;
	private String correo;
	private String representanteLegal;
	private byte[] mapaUbicacion;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public Direccion() {
	}

	public Direccion(Integer idDireccion, Persona persona, Integer idUbicacionGeografica, String callePrincipal,
			String calleSecundaria, String numeroCasa, String telefonoUno, String telefonoDos, String celular,
			String correo, Boolean eliminado, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idDireccion = idDireccion;
		this.persona = persona;
		this.idUbicacionGeografica = idUbicacionGeografica;
		this.callePrincipal = callePrincipal;
		this.calleSecundaria = calleSecundaria;
		this.numeroCasa = numeroCasa;
		this.telefonoUno = telefonoUno;
		this.telefonoDos = telefonoDos;
		this.celular = celular;
		this.correo = correo;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Direccion(Integer idDireccion, Persona persona, Integer idUbicacionGeografica, String callePrincipal,
			String calleSecundaria, String numeroCasa, String telefonoUno, String telefonoDos, String celular,
			String correo, String representanteLegal, byte[] mapaUbicacion, Boolean eliminado, String creacionUsuario,
			Date creacionFecha, String creacionEquipo, String modificaUsuario, Date modificaFecha,
			String modificaEquipo) {
		this.idDireccion = idDireccion;
		this.persona = persona;
		this.idUbicacionGeografica = idUbicacionGeografica;
		this.callePrincipal = callePrincipal;
		this.calleSecundaria = calleSecundaria;
		this.numeroCasa = numeroCasa;
		this.telefonoUno = telefonoUno;
		this.telefonoDos = telefonoDos;
		this.celular = celular;
		this.correo = correo;
		this.representanteLegal = representanteLegal;
		this.mapaUbicacion = mapaUbicacion;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_direccion", unique = true, nullable = false)
	public Integer getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(Integer idDireccion) {
		this.idDireccion = idDireccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "id_ubicacion_geografica", nullable = false)
	public Integer getIdUbicacionGeografica() {
		return this.idUbicacionGeografica;
	}

	public void setIdUbicacionGeografica(Integer idUbicacionGeografica) {
		this.idUbicacionGeografica = idUbicacionGeografica;
	}

	@Column(name = "calle_principal", nullable = false, length = 200)
	public String getCallePrincipal() {
		return this.callePrincipal;
	}

	public void setCallePrincipal(String callePrincipal) {
		this.callePrincipal = callePrincipal;
	}

	@Column(name = "calle_secundaria", nullable = false, length = 200)
	public String getCalleSecundaria() {
		return this.calleSecundaria;
	}

	public void setCalleSecundaria(String calleSecundaria) {
		this.calleSecundaria = calleSecundaria;
	}

	@Column(name = "numero_casa", nullable = false, length = 10)
	public String getNumeroCasa() {
		return this.numeroCasa;
	}

	public void setNumeroCasa(String numeroCasa) {
		this.numeroCasa = numeroCasa;
	}

	@Column(name = "telefono_uno", nullable = false, length = 10)
	public String getTelefonoUno() {
		return this.telefonoUno;
	}

	public void setTelefonoUno(String telefonoUno) {
		this.telefonoUno = telefonoUno;
	}

	@Column(name = "telefono_dos", nullable = false, length = 10)
	public String getTelefonoDos() {
		return this.telefonoDos;
	}

	public void setTelefonoDos(String telefonoDos) {
		this.telefonoDos = telefonoDos;
	}

	@Column(name = "celular", nullable = false, length = 10)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "correo", nullable = false, length = 200)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "representante_legal", length = 200)
	public String getRepresentanteLegal() {
		return this.representanteLegal;
	}

	public void setRepresentanteLegal(String representanteLegal) {
		this.representanteLegal = representanteLegal;
	}

	@Column(name = "mapa_ubicacion")
	public byte[] getMapaUbicacion() {
		return this.mapaUbicacion;
	}

	public void setMapaUbicacion(byte[] mapaUbicacion) {
		this.mapaUbicacion = mapaUbicacion;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
