package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fallecido generated by hbm2java
 */
@Entity
@Table(name = "fallecido", schema = "persona", catalog = "siisspolweb")
public class Fallecido implements java.io.Serializable {

	private Integer idFallecido;
	private Persona persona;
	private Date fechaDefuncion;
	private String causa;
	private Integer idUbicacionGeografica;
	private Boolean estadoAspirante;
	private String observacionSuicidio;
	private String observacionAspirante;
	private String estadoSuicidio;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public Fallecido() {
	}

	public Fallecido(Integer idFallecido, Persona persona, Date fechaDefuncion, String causa,
			Integer idUbicacionGeografica, Boolean estadoAspirante, String observacionSuicidio,
			String observacionAspirante, String estadoSuicidio, Boolean eliminado, String creacionUsuario,
			Date creacionFecha, String creacionEquipo, String modificaUsuario, Date modificaFecha,
			String modificaEquipo) {
		this.idFallecido = idFallecido;
		this.persona = persona;
		this.fechaDefuncion = fechaDefuncion;
		this.causa = causa;
		this.idUbicacionGeografica = idUbicacionGeografica;
		this.estadoAspirante = estadoAspirante;
		this.observacionSuicidio = observacionSuicidio;
		this.observacionAspirante = observacionAspirante;
		this.estadoSuicidio = estadoSuicidio;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_fallecido", unique = true, nullable = false)
	public Integer getIdFallecido() {
		return this.idFallecido;
	}

	public void setIdFallecido(Integer idFallecido) {
		this.idFallecido = idFallecido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "fecha_defuncion", nullable = false, length = 23)
	public Date getFechaDefuncion() {
		return this.fechaDefuncion;
	}

	public void setFechaDefuncion(Date fechaDefuncion) {
		this.fechaDefuncion = fechaDefuncion;
	}

	@Column(name = "causa", nullable = false, length = 100)
	public String getCausa() {
		return this.causa;
	}

	public void setCausa(String causa) {
		this.causa = causa;
	}

	@Column(name = "id_ubicacion_geografica", nullable = false)
	public Integer getIdUbicacionGeografica() {
		return this.idUbicacionGeografica;
	}

	public void setIdUbicacionGeografica(Integer idUbicacionGeografica) {
		this.idUbicacionGeografica = idUbicacionGeografica;
	}

	@Column(name = "estado_aspirante", nullable = false)
	public Boolean getEstadoAspirante() {
		return this.estadoAspirante;
	}

	public void setEstadoAspirante(Boolean estadoAspirante) {
		this.estadoAspirante = estadoAspirante;
	}

	@Column(name = "observacion_suicidio", nullable = false, length = 300)
	public String getObservacionSuicidio() {
		return this.observacionSuicidio;
	}

	public void setObservacionSuicidio(String observacionSuicidio) {
		this.observacionSuicidio = observacionSuicidio;
	}

	@Column(name = "observacion_aspirante", nullable = false, length = 200)
	public String getObservacionAspirante() {
		return this.observacionAspirante;
	}

	public void setObservacionAspirante(String observacionAspirante) {
		this.observacionAspirante = observacionAspirante;
	}

	@Column(name = "estado_suicidio", nullable = false, length = 10)
	public String getEstadoSuicidio() {
		return this.estadoSuicidio;
	}

	public void setEstadoSuicidio(String estadoSuicidio) {
		this.estadoSuicidio = estadoSuicidio;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
