package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Montepio generated by hbm2java
 */
@Entity
@Table(name = "montepio", schema = "persona", catalog = "siisspolweb")
public class Montepio implements java.io.Serializable {

	private Integer idMontepio;
	private OrigenDiscapacidad origenDiscapacidad;
	private TipoDiscapacidad tipoDiscapacidad;
	private CausantePension causantePension;
	private PersonaTipoSubtipo personaTipoSubtipo;
	private Parentesco parentesco;
	private BigDecimal porcentajeMontepio;
	private BigDecimal pensionMontepio;
	private Boolean habilitado;
	private String secuenciaHistorico;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public Montepio() {
	}

	public Montepio(Integer idMontepio, OrigenDiscapacidad origenDiscapacidad, CausantePension causantePension,
			PersonaTipoSubtipo personaTipoSubtipo, Parentesco parentesco, BigDecimal porcentajeMontepio,
			BigDecimal pensionMontepio, Boolean habilitado, String secuenciaHistorico, Boolean eliminado,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo) {
		this.idMontepio = idMontepio;
		this.origenDiscapacidad = origenDiscapacidad;
		this.causantePension = causantePension;
		this.personaTipoSubtipo = personaTipoSubtipo;
		this.parentesco = parentesco;
		this.porcentajeMontepio = porcentajeMontepio;
		this.pensionMontepio = pensionMontepio;
		this.habilitado = habilitado;
		this.secuenciaHistorico = secuenciaHistorico;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Montepio(Integer idMontepio, OrigenDiscapacidad origenDiscapacidad, TipoDiscapacidad tipoDiscapacidad,
			CausantePension causantePension, PersonaTipoSubtipo personaTipoSubtipo, Parentesco parentesco,
			BigDecimal porcentajeMontepio, BigDecimal pensionMontepio, Boolean habilitado, String secuenciaHistorico,
			Boolean eliminado, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idMontepio = idMontepio;
		this.origenDiscapacidad = origenDiscapacidad;
		this.tipoDiscapacidad = tipoDiscapacidad;
		this.causantePension = causantePension;
		this.personaTipoSubtipo = personaTipoSubtipo;
		this.parentesco = parentesco;
		this.porcentajeMontepio = porcentajeMontepio;
		this.pensionMontepio = pensionMontepio;
		this.habilitado = habilitado;
		this.secuenciaHistorico = secuenciaHistorico;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_montepio", unique = true, nullable = false)
	public Integer getIdMontepio() {
		return this.idMontepio;
	}

	public void setIdMontepio(Integer idMontepio) {
		this.idMontepio = idMontepio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_origen_discapacidad", nullable = false)
	public OrigenDiscapacidad getOrigenDiscapacidad() {
		return this.origenDiscapacidad;
	}

	public void setOrigenDiscapacidad(OrigenDiscapacidad origenDiscapacidad) {
		this.origenDiscapacidad = origenDiscapacidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_discapacidad")
	public TipoDiscapacidad getTipoDiscapacidad() {
		return this.tipoDiscapacidad;
	}

	public void setTipoDiscapacidad(TipoDiscapacidad tipoDiscapacidad) {
		this.tipoDiscapacidad = tipoDiscapacidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_causante_pension", nullable = false)
	public CausantePension getCausantePension() {
		return this.causantePension;
	}

	public void setCausantePension(CausantePension causantePension) {
		this.causantePension = causantePension;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_tipo_subtipo", nullable = false)
	public PersonaTipoSubtipo getPersonaTipoSubtipo() {
		return this.personaTipoSubtipo;
	}

	public void setPersonaTipoSubtipo(PersonaTipoSubtipo personaTipoSubtipo) {
		this.personaTipoSubtipo = personaTipoSubtipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_parentesco", nullable = false)
	public Parentesco getParentesco() {
		return this.parentesco;
	}

	public void setParentesco(Parentesco parentesco) {
		this.parentesco = parentesco;
	}

	@Column(name = "porcentaje_montepio", nullable = false, scale = 4)
	public BigDecimal getPorcentajeMontepio() {
		return this.porcentajeMontepio;
	}

	public void setPorcentajeMontepio(BigDecimal porcentajeMontepio) {
		this.porcentajeMontepio = porcentajeMontepio;
	}

	@Column(name = "pension_montepio", nullable = false, scale = 4)
	public BigDecimal getPensionMontepio() {
		return this.pensionMontepio;
	}

	public void setPensionMontepio(BigDecimal pensionMontepio) {
		this.pensionMontepio = pensionMontepio;
	}

	@Column(name = "habilitado", nullable = false)
	public Boolean getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Boolean habilitado) {
		this.habilitado = habilitado;
	}

	@Column(name = "secuencia_historico", nullable = false, length = 10)
	public String getSecuenciaHistorico() {
		return this.secuenciaHistorico;
	}

	public void setSecuenciaHistorico(String secuenciaHistorico) {
		this.secuenciaHistorico = secuenciaHistorico;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
