package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", schema = "persona", catalog = "siisspolweb")
public class Persona implements java.io.Serializable {

	private Integer idPersona;
	private TipoSexo tipoSexo;
	private TipoPersona tipoPersona;
	private EstadoCivil estadoCivil;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String nombre;
	private String identificacion;
	private Date fechaNacimiento;
	private Boolean juridico;
	private Integer idUbicacionGeografica;
	private String numeroAfiliado;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<PersonaTipoSubtipo> personaTipoSubtipos = new HashSet<PersonaTipoSubtipo>(0);
	private Set<Carpeta> carpetas = new HashSet<Carpeta>(0);
	private Set<CuentaBancaria> cuentaBancarias = new HashSet<CuentaBancaria>(0);
	private Set<PlazaActivo> plazaActivos = new HashSet<PlazaActivo>(0);
	private Set<Dependiente> dependientes = new HashSet<Dependiente>(0);
	private Set<Bloqueo> bloqueos = new HashSet<Bloqueo>(0);
	private Set<Direccion> direccions = new HashSet<Direccion>(0);
	private Set<Fallecido> fallecidos = new HashSet<Fallecido>(0);

	public Persona() {
	}

	public Persona(Integer idPersona, String apellidoPaterno, String apellidoMaterno, String nombre,
			String identificacion, Date fechaNacimiento, Boolean juridico, Integer idUbicacionGeografica,
			String numeroAfiliado, Boolean eliminado, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idPersona = idPersona;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.nombre = nombre;
		this.identificacion = identificacion;
		this.fechaNacimiento = fechaNacimiento;
		this.juridico = juridico;
		this.idUbicacionGeografica = idUbicacionGeografica;
		this.numeroAfiliado = numeroAfiliado;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Persona(Integer idPersona, TipoSexo tipoSexo, TipoPersona tipoPersona, EstadoCivil estadoCivil,
			String apellidoPaterno, String apellidoMaterno, String nombre, String identificacion, Date fechaNacimiento,
			Boolean juridico, Integer idUbicacionGeografica, String numeroAfiliado, Boolean eliminado,
			String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo, Set<PersonaTipoSubtipo> personaTipoSubtipos,
			Set<Carpeta> carpetas, Set<CuentaBancaria> cuentaBancarias, Set<PlazaActivo> plazaActivos,
			Set<Dependiente> dependientes, Set<Bloqueo> bloqueos, Set<Direccion> direccions,
			Set<Fallecido> fallecidos) {
		this.idPersona = idPersona;
		this.tipoSexo = tipoSexo;
		this.tipoPersona = tipoPersona;
		this.estadoCivil = estadoCivil;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.nombre = nombre;
		this.identificacion = identificacion;
		this.fechaNacimiento = fechaNacimiento;
		this.juridico = juridico;
		this.idUbicacionGeografica = idUbicacionGeografica;
		this.numeroAfiliado = numeroAfiliado;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.personaTipoSubtipos = personaTipoSubtipos;
		this.carpetas = carpetas;
		this.cuentaBancarias = cuentaBancarias;
		this.plazaActivos = plazaActivos;
		this.dependientes = dependientes;
		this.bloqueos = bloqueos;
		this.direccions = direccions;
		this.fallecidos = fallecidos;
	}

	@Id

	@Column(name = "id_persona", unique = true, nullable = false)
	public Integer getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Integer idPersona) {
		this.idPersona = idPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_sexo")
	public TipoSexo getTipoSexo() {
		return this.tipoSexo;
	}

	public void setTipoSexo(TipoSexo tipoSexo) {
		this.tipoSexo = tipoSexo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_persona")
	public TipoPersona getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(TipoPersona tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_civil")
	public EstadoCivil getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(EstadoCivil estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "apellido_paterno", nullable = false, length = 50)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "apellido_materno", nullable = false, length = 50)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "identificacion", nullable = false, length = 13)
	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "fecha_nacimiento", nullable = false, length = 23)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "juridico", nullable = false)
	public Boolean getJuridico() {
		return this.juridico;
	}

	public void setJuridico(Boolean juridico) {
		this.juridico = juridico;
	}

	@Column(name = "id_ubicacion_geografica", nullable = false)
	public Integer getIdUbicacionGeografica() {
		return this.idUbicacionGeografica;
	}

	public void setIdUbicacionGeografica(Integer idUbicacionGeografica) {
		this.idUbicacionGeografica = idUbicacionGeografica;
	}

	@Column(name = "numero_afiliado", nullable = false, length = 15)
	public String getNumeroAfiliado() {
		return this.numeroAfiliado;
	}

	public void setNumeroAfiliado(String numeroAfiliado) {
		this.numeroAfiliado = numeroAfiliado;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<PersonaTipoSubtipo> getPersonaTipoSubtipos() {
		return this.personaTipoSubtipos;
	}

	public void setPersonaTipoSubtipos(Set<PersonaTipoSubtipo> personaTipoSubtipos) {
		this.personaTipoSubtipos = personaTipoSubtipos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Carpeta> getCarpetas() {
		return this.carpetas;
	}

	public void setCarpetas(Set<Carpeta> carpetas) {
		this.carpetas = carpetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<CuentaBancaria> getCuentaBancarias() {
		return this.cuentaBancarias;
	}

	public void setCuentaBancarias(Set<CuentaBancaria> cuentaBancarias) {
		this.cuentaBancarias = cuentaBancarias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<PlazaActivo> getPlazaActivos() {
		return this.plazaActivos;
	}

	public void setPlazaActivos(Set<PlazaActivo> plazaActivos) {
		this.plazaActivos = plazaActivos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Dependiente> getDependientes() {
		return this.dependientes;
	}

	public void setDependientes(Set<Dependiente> dependientes) {
		this.dependientes = dependientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Bloqueo> getBloqueos() {
		return this.bloqueos;
	}

	public void setBloqueos(Set<Bloqueo> bloqueos) {
		this.bloqueos = bloqueos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Fallecido> getFallecidos() {
		return this.fallecidos;
	}

	public void setFallecidos(Set<Fallecido> fallecidos) {
		this.fallecidos = fallecidos;
	}

}
