package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Poder generated by hbm2java
 */
@Entity
@Table(name = "poder", schema = "persona", catalog = "siisspolweb")
public class Poder implements java.io.Serializable {

	private Integer idPoder;
	private Integer idPersonaAfiliado;
	private Integer idPersonaApoderado;
	private String causa;
	private Integer idParentesco;
	private Boolean habilitado;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public Poder() {
	}

	public Poder(Integer idPoder, Integer idPersonaAfiliado, Integer idPersonaApoderado, String causa,
			Integer idParentesco, Boolean habilitado, Boolean eliminado, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idPoder = idPoder;
		this.idPersonaAfiliado = idPersonaAfiliado;
		this.idPersonaApoderado = idPersonaApoderado;
		this.causa = causa;
		this.idParentesco = idParentesco;
		this.habilitado = habilitado;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_poder", unique = true, nullable = false)
	public Integer getIdPoder() {
		return this.idPoder;
	}

	public void setIdPoder(Integer idPoder) {
		this.idPoder = idPoder;
	}

	@Column(name = "id_persona_afiliado", nullable = false)
	public Integer getIdPersonaAfiliado() {
		return this.idPersonaAfiliado;
	}

	public void setIdPersonaAfiliado(Integer idPersonaAfiliado) {
		this.idPersonaAfiliado = idPersonaAfiliado;
	}

	@Column(name = "id_persona_apoderado", nullable = false)
	public Integer getIdPersonaApoderado() {
		return this.idPersonaApoderado;
	}

	public void setIdPersonaApoderado(Integer idPersonaApoderado) {
		this.idPersonaApoderado = idPersonaApoderado;
	}

	@Column(name = "causa", nullable = false, length = 200)
	public String getCausa() {
		return this.causa;
	}

	public void setCausa(String causa) {
		this.causa = causa;
	}

	@Column(name = "id_parentesco", nullable = false)
	public Integer getIdParentesco() {
		return this.idParentesco;
	}

	public void setIdParentesco(Integer idParentesco) {
		this.idParentesco = idParentesco;
	}

	@Column(name = "habilitado", nullable = false)
	public Boolean getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(Boolean habilitado) {
		this.habilitado = habilitado;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
