package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seguro generated by hbm2java
 */
@Entity
@Table(name = "seguro", schema = "persona", catalog = "siisspolweb")
public class Seguro implements java.io.Serializable {

	private Integer idSeguro;
	private PersonaTipoSubtipo personaTipoSubtipo;
	private Integer codigoSeguro;
	private BigDecimal valorInicial;
	private BigDecimal valorFinal;
	private BigDecimal valorTotal;
	private String numeroProyecto;
	private Date fechaProyecto;
	private String numeroBoletin;
	private Date fechaBoletin;
	private BigDecimal valorPagar;
	private BigDecimal valorPorPagar;
	private BigDecimal valorDeuda;
	private String observacionProyecto;
	private String observacionBoletin;
	private Boolean swProyecto;
	private BigDecimal baseCalculo;
	private BigDecimal sueldoTotal;
	private Integer seguroVida;
	private BigDecimal saldoImponible;
	private String informeSocialAntecedente;
	private String informeSocialObservacion;
	private BigDecimal valorLiquidacion;
	private Integer secuencia;
	private String informeSocioEconomico;
	private String informeAporte;
	private Date fechaInformeAporte;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<SeguroBeneficiario> seguroBeneficiarios = new HashSet<SeguroBeneficiario>(0);

	public Seguro() {
	}

	public Seguro(Integer idSeguro, PersonaTipoSubtipo personaTipoSubtipo, Integer codigoSeguro, Boolean swProyecto,
			BigDecimal baseCalculo, Integer secuencia, Boolean eliminado, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idSeguro = idSeguro;
		this.personaTipoSubtipo = personaTipoSubtipo;
		this.codigoSeguro = codigoSeguro;
		this.swProyecto = swProyecto;
		this.baseCalculo = baseCalculo;
		this.secuencia = secuencia;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Seguro(Integer idSeguro, PersonaTipoSubtipo personaTipoSubtipo, Integer codigoSeguro,
			BigDecimal valorInicial, BigDecimal valorFinal, BigDecimal valorTotal, String numeroProyecto,
			Date fechaProyecto, String numeroBoletin, Date fechaBoletin, BigDecimal valorPagar,
			BigDecimal valorPorPagar, BigDecimal valorDeuda, String observacionProyecto, String observacionBoletin,
			Boolean swProyecto, BigDecimal baseCalculo, BigDecimal sueldoTotal, Integer seguroVida,
			BigDecimal saldoImponible, String informeSocialAntecedente, String informeSocialObservacion,
			BigDecimal valorLiquidacion, Integer secuencia, String informeSocioEconomico, String informeAporte,
			Date fechaInformeAporte, Boolean eliminado, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo,
			Set<SeguroBeneficiario> seguroBeneficiarios) {
		this.idSeguro = idSeguro;
		this.personaTipoSubtipo = personaTipoSubtipo;
		this.codigoSeguro = codigoSeguro;
		this.valorInicial = valorInicial;
		this.valorFinal = valorFinal;
		this.valorTotal = valorTotal;
		this.numeroProyecto = numeroProyecto;
		this.fechaProyecto = fechaProyecto;
		this.numeroBoletin = numeroBoletin;
		this.fechaBoletin = fechaBoletin;
		this.valorPagar = valorPagar;
		this.valorPorPagar = valorPorPagar;
		this.valorDeuda = valorDeuda;
		this.observacionProyecto = observacionProyecto;
		this.observacionBoletin = observacionBoletin;
		this.swProyecto = swProyecto;
		this.baseCalculo = baseCalculo;
		this.sueldoTotal = sueldoTotal;
		this.seguroVida = seguroVida;
		this.saldoImponible = saldoImponible;
		this.informeSocialAntecedente = informeSocialAntecedente;
		this.informeSocialObservacion = informeSocialObservacion;
		this.valorLiquidacion = valorLiquidacion;
		this.secuencia = secuencia;
		this.informeSocioEconomico = informeSocioEconomico;
		this.informeAporte = informeAporte;
		this.fechaInformeAporte = fechaInformeAporte;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.seguroBeneficiarios = seguroBeneficiarios;
	}

	@Id

	@Column(name = "id_seguro", unique = true, nullable = false)
	public Integer getIdSeguro() {
		return this.idSeguro;
	}

	public void setIdSeguro(Integer idSeguro) {
		this.idSeguro = idSeguro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_tipo_subtipo_causante", nullable = false)
	public PersonaTipoSubtipo getPersonaTipoSubtipo() {
		return this.personaTipoSubtipo;
	}

	public void setPersonaTipoSubtipo(PersonaTipoSubtipo personaTipoSubtipo) {
		this.personaTipoSubtipo = personaTipoSubtipo;
	}

	@Column(name = "codigo_seguro", nullable = false)
	public Integer getCodigoSeguro() {
		return this.codigoSeguro;
	}

	public void setCodigoSeguro(Integer codigoSeguro) {
		this.codigoSeguro = codigoSeguro;
	}

	@Column(name = "valor_inicial", scale = 4)
	public BigDecimal getValorInicial() {
		return this.valorInicial;
	}

	public void setValorInicial(BigDecimal valorInicial) {
		this.valorInicial = valorInicial;
	}

	@Column(name = "valor_final", scale = 4)
	public BigDecimal getValorFinal() {
		return this.valorFinal;
	}

	public void setValorFinal(BigDecimal valorFinal) {
		this.valorFinal = valorFinal;
	}

	@Column(name = "valor_total", scale = 4)
	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	@Column(name = "numero_proyecto", length = 10)
	public String getNumeroProyecto() {
		return this.numeroProyecto;
	}

	public void setNumeroProyecto(String numeroProyecto) {
		this.numeroProyecto = numeroProyecto;
	}

	@Column(name = "fecha_proyecto", length = 23)
	public Date getFechaProyecto() {
		return this.fechaProyecto;
	}

	public void setFechaProyecto(Date fechaProyecto) {
		this.fechaProyecto = fechaProyecto;
	}

	@Column(name = "numero_boletin", length = 10)
	public String getNumeroBoletin() {
		return this.numeroBoletin;
	}

	public void setNumeroBoletin(String numeroBoletin) {
		this.numeroBoletin = numeroBoletin;
	}

	@Column(name = "fecha_boletin", length = 23)
	public Date getFechaBoletin() {
		return this.fechaBoletin;
	}

	public void setFechaBoletin(Date fechaBoletin) {
		this.fechaBoletin = fechaBoletin;
	}

	@Column(name = "valor_pagar", scale = 4)
	public BigDecimal getValorPagar() {
		return this.valorPagar;
	}

	public void setValorPagar(BigDecimal valorPagar) {
		this.valorPagar = valorPagar;
	}

	@Column(name = "valor_por_pagar", scale = 4)
	public BigDecimal getValorPorPagar() {
		return this.valorPorPagar;
	}

	public void setValorPorPagar(BigDecimal valorPorPagar) {
		this.valorPorPagar = valorPorPagar;
	}

	@Column(name = "valor_deuda", scale = 4)
	public BigDecimal getValorDeuda() {
		return this.valorDeuda;
	}

	public void setValorDeuda(BigDecimal valorDeuda) {
		this.valorDeuda = valorDeuda;
	}

	@Column(name = "observacion_proyecto")
	public String getObservacionProyecto() {
		return this.observacionProyecto;
	}

	public void setObservacionProyecto(String observacionProyecto) {
		this.observacionProyecto = observacionProyecto;
	}

	@Column(name = "observacion_boletin")
	public String getObservacionBoletin() {
		return this.observacionBoletin;
	}

	public void setObservacionBoletin(String observacionBoletin) {
		this.observacionBoletin = observacionBoletin;
	}

	@Column(name = "Sw_Proyecto", nullable = false)
	public Boolean getSwProyecto() {
		return this.swProyecto;
	}

	public void setSwProyecto(Boolean swProyecto) {
		this.swProyecto = swProyecto;
	}

	@Column(name = "base_calculo", nullable = false, scale = 4)
	public BigDecimal getBaseCalculo() {
		return this.baseCalculo;
	}

	public void setBaseCalculo(BigDecimal baseCalculo) {
		this.baseCalculo = baseCalculo;
	}

	@Column(name = "sueldo_total", scale = 4)
	public BigDecimal getSueldoTotal() {
		return this.sueldoTotal;
	}

	public void setSueldoTotal(BigDecimal sueldoTotal) {
		this.sueldoTotal = sueldoTotal;
	}

	@Column(name = "seguro_vida")
	public Integer getSeguroVida() {
		return this.seguroVida;
	}

	public void setSeguroVida(Integer seguroVida) {
		this.seguroVida = seguroVida;
	}

	@Column(name = "saldo_imponible", scale = 4)
	public BigDecimal getSaldoImponible() {
		return this.saldoImponible;
	}

	public void setSaldoImponible(BigDecimal saldoImponible) {
		this.saldoImponible = saldoImponible;
	}

	@Column(name = "informe_social_antecedente")
	public String getInformeSocialAntecedente() {
		return this.informeSocialAntecedente;
	}

	public void setInformeSocialAntecedente(String informeSocialAntecedente) {
		this.informeSocialAntecedente = informeSocialAntecedente;
	}

	@Column(name = "informe_social_observacion")
	public String getInformeSocialObservacion() {
		return this.informeSocialObservacion;
	}

	public void setInformeSocialObservacion(String informeSocialObservacion) {
		this.informeSocialObservacion = informeSocialObservacion;
	}

	@Column(name = "valor_liquidacion", scale = 4)
	public BigDecimal getValorLiquidacion() {
		return this.valorLiquidacion;
	}

	public void setValorLiquidacion(BigDecimal valorLiquidacion) {
		this.valorLiquidacion = valorLiquidacion;
	}

	@Column(name = "secuencia", nullable = false)
	public Integer getSecuencia() {
		return this.secuencia;
	}

	public void setSecuencia(Integer secuencia) {
		this.secuencia = secuencia;
	}

	@Column(name = "informe_socio_economico", length = 12)
	public String getInformeSocioEconomico() {
		return this.informeSocioEconomico;
	}

	public void setInformeSocioEconomico(String informeSocioEconomico) {
		this.informeSocioEconomico = informeSocioEconomico;
	}

	@Column(name = "informe_aporte", length = 12)
	public String getInformeAporte() {
		return this.informeAporte;
	}

	public void setInformeAporte(String informeAporte) {
		this.informeAporte = informeAporte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_informe_aporte", length = 10)
	public Date getFechaInformeAporte() {
		return this.fechaInformeAporte;
	}

	public void setFechaInformeAporte(Date fechaInformeAporte) {
		this.fechaInformeAporte = fechaInformeAporte;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seguro")
	public Set<SeguroBeneficiario> getSeguroBeneficiarios() {
		return this.seguroBeneficiarios;
	}

	public void setSeguroBeneficiarios(Set<SeguroBeneficiario> seguroBeneficiarios) {
		this.seguroBeneficiarios = seguroBeneficiarios;
	}

}
