package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SupervivenciaNovedad generated by hbm2java
 */
@Entity
@Table(name = "supervivencia_novedad", schema = "persona", catalog = "siisspolweb")
public class SupervivenciaNovedad implements java.io.Serializable {

	private Integer idSupervivenciaNovedad;
	private PersonaTipoSubtipo personaTipoSubtipo;
	private NovedadSuperior novedadSuperior;
	private Date fecha;
	private String formulario;
	private String observacion;
	private String observacionEducacion;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public SupervivenciaNovedad() {
	}

	public SupervivenciaNovedad(Integer idSupervivenciaNovedad, PersonaTipoSubtipo personaTipoSubtipo,
			NovedadSuperior novedadSuperior, Date fecha, String formulario, String observacion,
			String observacionEducacion, Boolean eliminado, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idSupervivenciaNovedad = idSupervivenciaNovedad;
		this.personaTipoSubtipo = personaTipoSubtipo;
		this.novedadSuperior = novedadSuperior;
		this.fecha = fecha;
		this.formulario = formulario;
		this.observacion = observacion;
		this.observacionEducacion = observacionEducacion;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_supervivencia_novedad", unique = true, nullable = false)
	public Integer getIdSupervivenciaNovedad() {
		return this.idSupervivenciaNovedad;
	}

	public void setIdSupervivenciaNovedad(Integer idSupervivenciaNovedad) {
		this.idSupervivenciaNovedad = idSupervivenciaNovedad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_tipo_subtipo", nullable = false)
	public PersonaTipoSubtipo getPersonaTipoSubtipo() {
		return this.personaTipoSubtipo;
	}

	public void setPersonaTipoSubtipo(PersonaTipoSubtipo personaTipoSubtipo) {
		this.personaTipoSubtipo = personaTipoSubtipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_novedad_superior", nullable = false)
	public NovedadSuperior getNovedadSuperior() {
		return this.novedadSuperior;
	}

	public void setNovedadSuperior(NovedadSuperior novedadSuperior) {
		this.novedadSuperior = novedadSuperior;
	}

	@Column(name = "fecha", nullable = false, length = 23)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "formulario", nullable = false, length = 10)
	public String getFormulario() {
		return this.formulario;
	}

	public void setFormulario(String formulario) {
		this.formulario = formulario;
	}

	@Column(name = "observacion", nullable = false, length = 100)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "observacion_educacion", nullable = false, length = 100)
	public String getObservacionEducacion() {
		return this.observacionEducacion;
	}

	public void setObservacionEducacion(String observacionEducacion) {
		this.observacionEducacion = observacionEducacion;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
