package ec.org.isspol.persistence.entities.persona;
// Generated 03-may-2017 11:11:44 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VidaInstitucional generated by hbm2java
 */
@Entity
@Table(name = "vida_institucional", schema = "persona", catalog = "siisspolweb")
public class VidaInstitucional implements java.io.Serializable {

	private String idVidaInstitucional;
	private TipoNovedad tipoNovedad;
	private Grado grado;
	private TipoDocumento tipoDocumento;
	private PersonaTipoSubtipo personaTipoSubtipo;
	private Date fechaNovedad;
	private String observacion;
	private String fechaRegistro;
	private Boolean estado;
	private Boolean eliminado;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public VidaInstitucional() {
	}

	public VidaInstitucional(String idVidaInstitucional, TipoNovedad tipoNovedad, TipoDocumento tipoDocumento,
			PersonaTipoSubtipo personaTipoSubtipo, Date fechaNovedad, String observacion, String fechaRegistro,
			Boolean estado, Boolean eliminado, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idVidaInstitucional = idVidaInstitucional;
		this.tipoNovedad = tipoNovedad;
		this.tipoDocumento = tipoDocumento;
		this.personaTipoSubtipo = personaTipoSubtipo;
		this.fechaNovedad = fechaNovedad;
		this.observacion = observacion;
		this.fechaRegistro = fechaRegistro;
		this.estado = estado;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public VidaInstitucional(String idVidaInstitucional, TipoNovedad tipoNovedad, Grado grado,
			TipoDocumento tipoDocumento, PersonaTipoSubtipo personaTipoSubtipo, Date fechaNovedad, String observacion,
			String fechaRegistro, Boolean estado, Boolean eliminado, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idVidaInstitucional = idVidaInstitucional;
		this.tipoNovedad = tipoNovedad;
		this.grado = grado;
		this.tipoDocumento = tipoDocumento;
		this.personaTipoSubtipo = personaTipoSubtipo;
		this.fechaNovedad = fechaNovedad;
		this.observacion = observacion;
		this.fechaRegistro = fechaRegistro;
		this.estado = estado;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_vida_institucional", unique = true, nullable = false, length = 10)
	public String getIdVidaInstitucional() {
		return this.idVidaInstitucional;
	}

	public void setIdVidaInstitucional(String idVidaInstitucional) {
		this.idVidaInstitucional = idVidaInstitucional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_novedad", nullable = false)
	public TipoNovedad getTipoNovedad() {
		return this.tipoNovedad;
	}

	public void setTipoNovedad(TipoNovedad tipoNovedad) {
		this.tipoNovedad = tipoNovedad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grado_real")
	public Grado getGrado() {
		return this.grado;
	}

	public void setGrado(Grado grado) {
		this.grado = grado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_documento", nullable = false)
	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona_tipo_subtipo", nullable = false)
	public PersonaTipoSubtipo getPersonaTipoSubtipo() {
		return this.personaTipoSubtipo;
	}

	public void setPersonaTipoSubtipo(PersonaTipoSubtipo personaTipoSubtipo) {
		this.personaTipoSubtipo = personaTipoSubtipo;
	}

	@Column(name = "fecha_novedad", nullable = false, length = 23)
	public Date getFechaNovedad() {
		return this.fechaNovedad;
	}

	public void setFechaNovedad(Date fechaNovedad) {
		this.fechaNovedad = fechaNovedad;
	}

	@Column(name = "observacion", nullable = false, length = 500)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "fecha_registro", nullable = false, length = 10)
	public String getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(String fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "estado", nullable = false)
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "eliminado", nullable = false)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
