package ec.org.isspol.persistence.entities.security;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.*;
import javax.persistence.*;

/**
 * GrupoModulo generated by hbm2java
 */
@Entity
@Table(name = "grupo_modulo", schema = "seguridad", catalog = "siisspolweb")
public class GrupoModulo extends AuditEntity implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_grupo_modulo", unique = true, nullable = false)
    private Integer idGrupoModulo;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_modulo", nullable = false)
    private Modulo modulo;
    @Column(name = "nombre", nullable = false, length = 25)
    private String nombre;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "grupoModulo")
    private Collection<Opcion> listaOpciones = new ArrayList<Opcion>();

    public Integer getIdGrupoModulo() {
        return this.idGrupoModulo;
    }

    public void setIdGrupoModulo(Integer idGrupoModulo) {
        this.idGrupoModulo = idGrupoModulo;
    }

    public Modulo getModulo() {
        return this.modulo;
    }

    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Collection<Opcion> getListaOpciones() {
        return listaOpciones;
    }

    public void setListaOpciones(Collection<Opcion> listaOpciones) {
        this.listaOpciones = listaOpciones;
    }
}
