package ec.org.isspol.persistence.entities.security;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.*;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * GrupoUsuario generated by hbm2java
 */
@Entity
@Table(name = "grupo_usuario", schema = "seguridad", catalog = "siisspolweb",
		uniqueConstraints = @UniqueConstraint(columnNames = {"id_grupo", "id_usuario" }))
public class GrupoUsuario implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_grupo_usuario", unique = true, nullable = false)
	private Integer idGrupoUsuario;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo", nullable = false)
	private Grupo grupo;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	private Usuario usuario;
	@Column(name = "estado", nullable = false, length = 1)
	private Integer estado;
	@Column(name = "tiene_vencimiento", nullable = false)
	private Boolean tieneVencimiento;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_vencimiento", length = 23)
	private Date fechaVencimiento;
	@Column(name = "eliminado", nullable = false)
	private Boolean eliminado;
	@Column(name = "creacion_usuario", nullable = false, length = 20)
	private String creacionUsuario;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	private Date creacionFecha;
	@Column(name = "creacion_equipo", nullable = false, length = 20)
	private String creacionEquipo;
	@Column(name = "modifica_usuario", nullable = false, length = 20)
	private String modificaUsuario;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	private Date modificaFecha;
	@Column(name = "modifica_equipo", nullable = false, length = 20)
	private String modificaEquipo;

	public GrupoUsuario() {
	}

	public GrupoUsuario(Integer idGrupoUsuario, Grupo grupo, Usuario usuario, Integer estado, Boolean tieneVencimiento,
			Boolean eliminado, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idGrupoUsuario = idGrupoUsuario;
		this.grupo = grupo;
		this.usuario = usuario;
		this.estado = estado;
		this.tieneVencimiento = tieneVencimiento;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public GrupoUsuario(Integer idGrupoUsuario, Grupo grupo, Usuario usuario, Integer estado, Boolean tieneVencimiento,
			Date fechaVencimiento, Boolean eliminado, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idGrupoUsuario = idGrupoUsuario;
		this.grupo = grupo;
		this.usuario = usuario;
		this.estado = estado;
		this.tieneVencimiento = tieneVencimiento;
		this.fechaVencimiento = fechaVencimiento;
		this.eliminado = eliminado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Integer getIdGrupoUsuario() {
		return this.idGrupoUsuario;
	}

	public void setIdGrupoUsuario(Integer idGrupoUsuario) {
		this.idGrupoUsuario = idGrupoUsuario;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	public Boolean getTieneVencimiento() {
		return this.tieneVencimiento;
	}

	public void setTieneVencimiento(Boolean tieneVencimiento) {
		this.tieneVencimiento = tieneVencimiento;
	}

	public Date getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(Date fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}

	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
