package ec.org.isspol.persistence.entities.security;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import javax.persistence.*;
import java.util.*;

/**
 * NivelEstructuraOrg generated by hbm2java
 */
@Entity
@Table(name = "nivel_estructura_org", schema = "seguridad", catalog = "siisspolweb")
public class NivelEstructuraOrg extends AuditEntity implements java.io.Serializable {

	@Id
	@Column(name = "id_nivel_estructura_org", unique = true, nullable = false)
	private Integer idNivelEstructuraOrg;

	@Column(name = "largo_codigo", nullable = false)
	private short largoCodigo;

	@Column(name = "descripcion", nullable = false, length = 50)
	private String descripcion;

	@Column(name = "icono", nullable = false)
	private Integer icono;

	@Column(name = "icono_css", nullable = false)
	private String iconoCss;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivel")
	private Collection<EstructuraOrganizacional> listaEstrOrg = new ArrayList<>();

	public NivelEstructuraOrg() {
	}

	public String getIconoCss() {
		return iconoCss;
	}

	public void setIconoCss(String iconoCss) {
		this.iconoCss = iconoCss;
	}

	public Integer getIdNivelEstructuraOrg() {
		return idNivelEstructuraOrg;
	}

	public void setIdNivelEstructuraOrg(Integer idNivelEstructuraOrg) {
		this.idNivelEstructuraOrg = idNivelEstructuraOrg;
	}

	public short getLargoCodigo() {
		return largoCodigo;
	}

	public void setLargoCodigo(short largoCodigo) {
		this.largoCodigo = largoCodigo;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getIcono() {
		return icono;
	}

	public void setIcono(Integer icono) {
		this.icono = icono;
	}

	public Collection<EstructuraOrganizacional> getListaEstrOrg() {
		return listaEstrOrg;
	}

	public void setListaEstrOrg(Collection<EstructuraOrganizacional> listaEstrOrg) {
		this.listaEstrOrg = listaEstrOrg;
	}
}
