package ec.org.isspol.persistence.entities.security;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Opcion generated by hbm2java
 */
@Entity
@Table(name = "opcion", schema = "seguridad", catalog = "siisspolweb")
public class Opcion implements java.io.Serializable {

	private Integer idOpcion;
	private CarpetaOpcion carpetaOpcion;
	private Modulo modulo;
	private Icono icono;
	private GrupoModulo grupoModulo;
	private String nombre;
	private String objeto;
	private Integer orden;
	private String descripcion;
	private String parametro;
	private String tipoAbrir;
	private Boolean visible;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;
	private Set<Permiso> permisos = new HashSet<Permiso>(0);
	private Set<Favorito> favoritos = new HashSet<Favorito>(0);
	private Set<OpcionUso> opcionUsos = new HashSet<OpcionUso>(0);

	public Opcion() {
	}

	public Opcion(Integer idOpcion, CarpetaOpcion carpetaOpcion, Icono icono, String nombre, String objeto,
			Integer orden, String tipoAbrir, Boolean visible, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idOpcion = idOpcion;
		this.carpetaOpcion = carpetaOpcion;
		this.icono = icono;
		this.nombre = nombre;
		this.objeto = objeto;
		this.orden = orden;
		this.tipoAbrir = tipoAbrir;
		this.visible = visible;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public Opcion(Integer idOpcion, CarpetaOpcion carpetaOpcion, Modulo modulo, Icono icono, GrupoModulo grupoModulo,
			String nombre, String objeto, Integer orden, String descripcion, String parametro, String tipoAbrir,
			Boolean visible, String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
			Date modificaFecha, String modificaEquipo, Set<Permiso> permisos, Set<Favorito> favoritos,
			Set<OpcionUso> opcionUsos) {
		this.idOpcion = idOpcion;
		this.carpetaOpcion = carpetaOpcion;
		this.modulo = modulo;
		this.icono = icono;
		this.grupoModulo = grupoModulo;
		this.nombre = nombre;
		this.objeto = objeto;
		this.orden = orden;
		this.descripcion = descripcion;
		this.parametro = parametro;
		this.tipoAbrir = tipoAbrir;
		this.visible = visible;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
		this.permisos = permisos;
		this.favoritos = favoritos;
		this.opcionUsos = opcionUsos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_opcion", unique = true, nullable = false)
	public Integer getIdOpcion() {
		return this.idOpcion;
	}

	public void setIdOpcion(Integer idOpcion) {
		this.idOpcion = idOpcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_carpeta_opcion", nullable = false)
	public CarpetaOpcion getCarpetaOpcion() {
		return this.carpetaOpcion;
	}

	public void setCarpetaOpcion(CarpetaOpcion carpetaOpcion) {
		this.carpetaOpcion = carpetaOpcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_modulo")
	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_icono", nullable = false)
	public Icono getIcono() {
		return this.icono;
	}

	public void setIcono(Icono icono) {
		this.icono = icono;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_modulo")
	public GrupoModulo getGrupoModulo() {
		return this.grupoModulo;
	}

	public void setGrupoModulo(GrupoModulo grupoModulo) {
		this.grupoModulo = grupoModulo;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "objeto", nullable = false, length = 100)
	public String getObjeto() {
		return this.objeto;
	}

	public void setObjeto(String objeto) {
		this.objeto = objeto;
	}

	@Column(name = "orden", nullable = false)
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "parametro", length = 100)
	public String getParametro() {
		return this.parametro;
	}

	public void setParametro(String parametro) {
		this.parametro = parametro;
	}

	@Column(name = "tipo_abrir", nullable = false, length = 2)
	public String getTipoAbrir() {
		return this.tipoAbrir;
	}

	public void setTipoAbrir(String tipoAbrir) {
		this.tipoAbrir = tipoAbrir;
	}

	@Column(name = "visible", nullable = false)
	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcion")
	public Set<Permiso> getPermisos() {
		return this.permisos;
	}

	public void setPermisos(Set<Permiso> permisos) {
		this.permisos = permisos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcion")
	public Set<Favorito> getFavoritos() {
		return this.favoritos;
	}

	public void setFavoritos(Set<Favorito> favoritos) {
		this.favoritos = favoritos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcion")
	public Set<OpcionUso> getOpcionUsos() {
		return this.opcionUsos;
	}

	public void setOpcionUsos(Set<OpcionUso> opcionUsos) {
		this.opcionUsos = opcionUsos;
	}

}
