package ec.org.isspol.persistence.entities.security;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * UsuarioOficina generated by hbm2java
 */
@Entity
@Table(name = "usuario_oficina", schema = "seguridad", catalog = "siisspolweb",
        uniqueConstraints = @UniqueConstraint(columnNames = {"id_oficina", "id_usuario"}))
public class UsuarioOficina implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_usuario_oficina", unique = true, nullable = false)
    private Integer idUsuarioOficina;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_oficina", nullable = false)
    private Oficina oficina;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_usuario", nullable = false)
    private Usuario usuario;
    @Column(name = "eliminado", nullable = false)
    private Boolean eliminado;
    @Column(name = "creacion_usuario", nullable = false, length = 20)
    private String creacionUsuario;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "creacion_fecha", nullable = false, length = 23)
    private Date creacionFecha;
    @Column(name = "creacion_equipo", nullable = false, length = 20)
    private String creacionEquipo;
    @Column(name = "modifica_usuario", nullable = false, length = 20)
    private String modificaUsuario;
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "modifica_fecha", nullable = false, length = 23)
    private Date modificaFecha;
    @Column(name = "modifica_equipo", nullable = false, length = 20)
    private String modificaEquipo;

    public UsuarioOficina() {
    }

    public UsuarioOficina(Integer idUsuarioOficina, Usuario usuario, Oficina oficina, Boolean eliminado,
                           String creacionUsuario, Date creacionFecha, String creacionEquipo, String modificaUsuario,
                           Date modificaFecha, String modificaEquipo) {
        this.idUsuarioOficina = idUsuarioOficina;
        this.usuario = usuario;
        this.oficina = oficina;
        this.eliminado = eliminado;
        this.creacionUsuario = creacionUsuario;
        this.creacionFecha = creacionFecha;
        this.creacionEquipo = creacionEquipo;
        this.modificaUsuario = modificaUsuario;
        this.modificaFecha = modificaFecha;
        this.modificaEquipo = modificaEquipo;
    }

    public Integer getIdUsuarioOficina() {
        return idUsuarioOficina;
    }

    public void setIdUsuarioOficina(Integer idUsuarioOficina) {
        this.idUsuarioOficina = idUsuarioOficina;
    }

    public Oficina getOficina() {
        return oficina;
    }

    public void setOficina(Oficina oficina) {
        this.oficina = oficina;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Boolean getEliminado() {
        return eliminado;
    }

    public void setEliminado(Boolean eliminado) {
        this.eliminado = eliminado;
    }

    public String getCreacionUsuario() {
        return creacionUsuario;
    }

    public void setCreacionUsuario(String creacionUsuario) {
        this.creacionUsuario = creacionUsuario;
    }

    public Date getCreacionFecha() {
        return creacionFecha;
    }

    public void setCreacionFecha(Date creacionFecha) {
        this.creacionFecha = creacionFecha;
    }

    public String getCreacionEquipo() {
        return creacionEquipo;
    }

    public void setCreacionEquipo(String creacionEquipo) {
        this.creacionEquipo = creacionEquipo;
    }

    public String getModificaUsuario() {
        return modificaUsuario;
    }

    public void setModificaUsuario(String modificaUsuario) {
        this.modificaUsuario = modificaUsuario;
    }

    public Date getModificaFecha() {
        return modificaFecha;
    }

    public void setModificaFecha(Date modificaFecha) {
        this.modificaFecha = modificaFecha;
    }

    public String getModificaEquipo() {
        return modificaEquipo;
    }

    public void setModificaEquipo(String modificaEquipo) {
        this.modificaEquipo = modificaEquipo;
    }
}
