package ec.org.isspol.persistence.entities.security;
// Generated 21-abr-2017 12:20:59 by Hibernate Tools 4.0.1.Final

import ec.org.isspol.persistence.entities.comun.UbicacionGeografica;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuarioUbicacionGeografica generated by hbm2java
 */
@Entity
@Table(name = "usuario_ubicacion_geografica", schema = "seguridad", catalog = "siisspolweb")
public class UsuarioUbicacionGeografica implements java.io.Serializable {

	private Integer idUsuarioUbicacionGeografica;
	private UbicacionGeografica ubicacionGeografica;
	private Usuario usuario;
	private char estado;
	private Integer idDiaMes;
	private String creacionUsuario;
	private Date creacionFecha;
	private String creacionEquipo;
	private String modificaUsuario;
	private Date modificaFecha;
	private String modificaEquipo;

	public UsuarioUbicacionGeografica() {
	}

	public UsuarioUbicacionGeografica(Integer idUsuarioUbicacionGeografica, UbicacionGeografica ubicacionGeografica,
			Usuario usuario, char estado, String creacionUsuario, Date creacionFecha, String creacionEquipo,
			String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idUsuarioUbicacionGeografica = idUsuarioUbicacionGeografica;
		this.ubicacionGeografica = ubicacionGeografica;
		this.usuario = usuario;
		this.estado = estado;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	public UsuarioUbicacionGeografica(Integer idUsuarioUbicacionGeografica, UbicacionGeografica ubicacionGeografica,
			Usuario usuario, char estado, Integer idDiaMes, String creacionUsuario, Date creacionFecha,
			String creacionEquipo, String modificaUsuario, Date modificaFecha, String modificaEquipo) {
		this.idUsuarioUbicacionGeografica = idUsuarioUbicacionGeografica;
		this.ubicacionGeografica = ubicacionGeografica;
		this.usuario = usuario;
		this.estado = estado;
		this.idDiaMes = idDiaMes;
		this.creacionUsuario = creacionUsuario;
		this.creacionFecha = creacionFecha;
		this.creacionEquipo = creacionEquipo;
		this.modificaUsuario = modificaUsuario;
		this.modificaFecha = modificaFecha;
		this.modificaEquipo = modificaEquipo;
	}

	@Id

	@Column(name = "id_usuario_ubicacion_geografica", unique = true, nullable = false)
	public Integer getIdUsuarioUbicacionGeografica() {
		return this.idUsuarioUbicacionGeografica;
	}

	public void setIdUsuarioUbicacionGeografica(Integer idUsuarioUbicacionGeografica) {
		this.idUsuarioUbicacionGeografica = idUsuarioUbicacionGeografica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ubicacion_geografica", nullable = false)
	public UbicacionGeografica getUbicacionGeografica() {
		return this.ubicacionGeografica;
	}

	public void setUbicacionGeografica(UbicacionGeografica ubicacionGeografica) {
		this.ubicacionGeografica = ubicacionGeografica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "id_dia_mes")
	public Integer getIdDiaMes() {
		return this.idDiaMes;
	}

	public void setIdDiaMes(Integer idDiaMes) {
		this.idDiaMes = idDiaMes;
	}

	@Column(name = "creacion_usuario", nullable = false, length = 20)
	public String getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(String creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion_fecha", nullable = false, length = 23)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "creacion_equipo", nullable = false, length = 20)
	public String getCreacionEquipo() {
		return this.creacionEquipo;
	}

	public void setCreacionEquipo(String creacionEquipo) {
		this.creacionEquipo = creacionEquipo;
	}

	@Column(name = "modifica_usuario", nullable = false, length = 20)
	public String getModificaUsuario() {
		return this.modificaUsuario;
	}

	public void setModificaUsuario(String modificaUsuario) {
		this.modificaUsuario = modificaUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifica_fecha", nullable = false, length = 23)
	public Date getModificaFecha() {
		return this.modificaFecha;
	}

	public void setModificaFecha(Date modificaFecha) {
		this.modificaFecha = modificaFecha;
	}

	@Column(name = "modifica_equipo", nullable = false, length = 20)
	public String getModificaEquipo() {
		return this.modificaEquipo;
	}

	public void setModificaEquipo(String modificaEquipo) {
		this.modificaEquipo = modificaEquipo;
	}

}
